window.itemData = [

  // ── HELD ITEMS (battle effects) ──────────────────────────────────────────

  { name: "Ability Shield",    icon: "assets/items/ability-shield.png",    effect: "Prevents the holder's Ability from being changed or suppressed by any effect, including ability-ignoring abilities such as Mold Breaker." },
  { name: "Air Balloon",       icon: "assets/items/air-balloon.png",       effect: "Makes the holder ungrounded and immune to Ground-type moves. The balloon bursts when the holder is hit by any damaging move." },
  { name: "Amulet Coin",       icon: "assets/items/amulet-coin.png",       effect: "Doubles prize money earned after battle if the holder participated. Also doubles coins from Pay Day." },
  { name: "Assault Vest",      icon: "assets/items/assault-vest.png",      effect: "Raises the holder's Special Defense by 50%, but prevents the holder from selecting any status moves (except Me First)." },
  { name: "Big Root",          icon: "assets/items/big-root.png",          effect: "Increases HP restored by draining moves and Ingrain by 30%. Also increases HP drain from Leech Seed." },
  { name: "Binding Band",      icon: "assets/items/binding-band.png",      effect: "Increases damage dealt by partial-trapping moves (Wrap, Bind, etc.) from 1/16 to 1/6 of the target's max HP per turn." },
  { name: "Blunder Policy",    icon: "assets/items/blunder-policy.png",    effect: "If the holder misses a move due to its accuracy check failing, sharply raises holder's Speed. Consumed after use." },
  { name: "Bright Powder",     icon: "assets/items/bright-powder.png",     effect: "Lowers the opposing Pokémon's accuracy by 10% when targeting the holder." },
  { name: "Choice Band",       icon: "assets/items/choice-band.png",       effect: "Raises the holder's Attack by 50%, but locks it into the first move it uses until it switches out." },
  { name: "Choice Scarf",      icon: "assets/items/choice-scarf.png",      effect: "Raises the holder's Speed by 50%, but locks it into the first move it uses until it switches out." },
  { name: "Choice Specs",      icon: "assets/items/choice-specs.png",      effect: "Raises the holder's Special Attack by 50%, but locks it into the first move it uses until it switches out." },
  { name: "Clear Amulet",      icon: "assets/items/clear-amulet.png",      effect: "Prevents foes from lowering the holder's stats. Does not block the holder's own stat drops." },
  { name: "Covert Cloak",      icon: "assets/items/covert-cloak.png",      effect: "Protects the holder from the additional effects of moves (e.g., flinching, burns, freezes from secondary effects)." },
  { name: "Damp Rock",         icon: "assets/items/damp-rock.png",         effect: "Extends the duration of Rain Dance summoned by the holder from 5 to 8 turns." },
  { name: "Destiny Knot",      icon: "assets/items/destiny-knot.png",      effect: "If the holder becomes attracted (infatuated), the attractor also becomes attracted. Also passes 5 IVs in breeding." },
  { name: "Eject Button",      icon: "assets/items/eject-button.png",      effect: "Forces the holder to immediately switch out when it is hit by a damaging move. Consumed after use." },
  { name: "Eject Pack",        icon: "assets/items/eject-pack.png",        effect: "Forces the holder to immediately switch out when any of its stats are lowered. Consumed after use." },
  { name: "Expert Belt",       icon: "assets/items/expert-belt.png",       effect: "Increases the power of the holder's super-effective moves by 20%." },
  { name: "Flame Orb",         icon: "assets/items/flame-orb.png",         effect: "Burns the holder at the end of each turn. Can be used with Guts or Facade for strategic purposes." },
  { name: "Float Stone",       icon: "assets/items/float-stone.png",       effect: "Halves the holder's weight, which affects moves like Low Kick and Grass Knot that scale with weight." },
  { name: "Focus Band",        icon: "assets/items/focus-band.png",        effect: "Gives the holder a 10% chance to survive an otherwise KO-dealing hit with 1 HP. Not consumed on activation." },
  { name: "Focus Sash",        icon: "assets/items/focus-sash.png",        effect: "If the holder is at full HP, allows it to survive any single hit that would KO it with 1 HP. Consumed after use." },
  { name: "Full Incense",      icon: "assets/items/full-incense.png",      effect: "Causes the holder to always move last within its priority bracket, like Lagging Tail. Breeding incense for Munchlax." },
  { name: "Grip Claw",         icon: "assets/items/grip-claw.png",         effect: "Extends partial-trapping moves (Wrap, Bind, etc.) to always last exactly 7 turns. Also reveals exact damage taken." },
  { name: "Heat Rock",         icon: "assets/items/heat-rock.png",         effect: "Extends the duration of Sunny Day summoned by the holder from 5 to 8 turns." },
  { name: "Heavy-Duty Boots",  icon: "assets/items/heavy-duty-boots.png",  effect: "Makes the holder completely unaffected by entry hazards such as Spikes, Toxic Spikes, Stealth Rock, and Sticky Web." },
  { name: "Icy Rock",          icon: "assets/items/icy-rock.png",          effect: "Extends the duration of Hail summoned by the holder from 5 to 8 turns." },
  { name: "Iron Ball",         icon: "assets/items/iron-ball.png",         effect: "Halves the holder's Speed. Grounds the holder, making it vulnerable to Ground-type moves and entry hazards. Reverses Trick Room speed mechanics." },
  { name: "King's Rock",       icon: "assets/items/kings-rock.png",        effect: "Gives the holder's moves that don't normally flinch a 10% chance to flinch. Also causes Bite, Headbutt, etc. to flinch." },
  { name: "Lagging Tail",      icon: "assets/items/lagging-tail.png",      effect: "Causes the holder to always move last within its priority bracket, regardless of Speed." },
  { name: "Lax Incense",       icon: "assets/items/lax-incense.png",       effect: "Lowers the opposing Pokémon's accuracy by 10% when targeting the holder. Breeding incense for Wynaut." },
  { name: "Leek",              icon: "assets/items/leek.png",              effect: "Raises the critical hit ratio of Farfetch'd and Sirfetch'd by 2 stages, greatly increasing the chance of landing critical hits." },
  { name: "Life Orb",          icon: "assets/items/life-orb.png",          effect: "Boosts the power of the holder's moves by 30%. The holder loses 10% of its max HP after each attack." },
  { name: "Light Clay",        icon: "assets/items/light-clay.png",        effect: "Extends the duration of Reflect and Light Screen set up by the holder from 5 to 8 turns." },
  { name: "Loaded Dice",       icon: "assets/items/loaded-dice.png",       effect: "Multi-hit moves used by the holder always hit 4 or 5 times, eliminating the lower-hit-count outcomes." },
  { name: "Luck Incense",      icon: "assets/items/luck-incense.png",      effect: "Doubles prize money earned after battle if the holder participated. Also doubles coins from Pay Day. Breeding incense for Happiny." },
  { name: "Lucky Punch",       icon: "assets/items/lucky-punch.png",       effect: "Doubles the critical hit ratio of Chansey and Blissey, significantly increasing their chance of landing critical hits." },
  { name: "Macho Brace",       icon: "assets/items/macho-brace.png",       effect: "Doubles EV gain from battles. Halves the holder's Speed in battle." },
  { name: "Mental Herb",       icon: "assets/items/mental-herb.png",       effect: "Cures attraction, Taunt, Encore, Torment, Heal Block, and Disable affecting the holder once. Consumed after use." },
  { name: "Metronome",         icon: "assets/items/metronome.png",         effect: "Each consecutive use of the same move by the holder increases that move's power by 10% (capped at +100%). Resets on switching or using a different move." },
  { name: "Mirror Herb",       icon: "assets/items/mirror-herb.png",       effect: "Once per battle, when an opposing Pokémon raises a stat, the holder copies that stat raise. Consumed after activation." },
  { name: "Muscle Band",       icon: "assets/items/muscle-band.png",       effect: "Increases the power of the holder's physical moves by 10%." },
  { name: "Power Herb",        icon: "assets/items/power-herb.png",        effect: "Allows the holder to use a two-turn move (like Solar Beam, Fly, Dive) in one turn. Consumed after use." },
  { name: "Protective Pads",   icon: "assets/items/protective-pads.png",   effect: "The holder's moves do not make contact, protecting it from contact-based secondary effects like Rough Skin, Static, or Iron Barbs." },
  { name: "Punching Glove",    icon: "assets/items/punching-glove.png",    effect: "Increases the power of the holder's punching moves by 10%. Also prevents those moves from making contact." },
  { name: "Quick Claw",        icon: "assets/items/quick-claw.png",        effect: "Gives the holder a 20% chance to move first within its priority bracket, regardless of Speed." },
  { name: "Razor Claw",        icon: "assets/items/razor-claw.png",        effect: "Raises the holder's critical hit ratio by 1 stage. Evolves Sneasel into Weavile when held at night." },
  { name: "Razor Fang",        icon: "assets/items/razor-fang.png",        effect: "Gives the holder's moves a 10% chance to cause flinching. Evolves Gligar into Gliscor when held at night." },
  { name: "Red Card",          icon: "assets/items/red-card.png",          effect: "When the holder is hit by a damaging move, forces the attacker to switch out. Consumed after activation." },
  { name: "Ring Target",       icon: "assets/items/ring-target.png",       effect: "Removes the holder's type immunities, making it vulnerable to moves it would otherwise be immune to." },
  { name: "Rocky Helmet",      icon: "assets/items/rocky-helmet.png",      effect: "When the holder is hit by a contact move, the attacker takes damage equal to 1/6 of their max HP." },
  { name: "Room Service",      icon: "assets/items/room-service.png",      effect: "Lowers the holder's Speed when Trick Room is activated. Consumed after activation." },
  { name: "Safety Goggles",    icon: "assets/items/safety-goggles.png",    effect: "Protects the holder from weather damage (Sandstorm, Hail) and from powder and spore moves like Sleep Powder and Spore." },
  { name: "Scope Lens",        icon: "assets/items/scope-lens.png",        effect: "Raises the holder's critical hit ratio by 1 stage, increasing the chance of landing critical hits." },
  { name: "Shed Shell",        icon: "assets/items/shed-shell.png",        effect: "Allows the holder to switch out even when it would normally be prevented by trapping moves or abilities." },
  { name: "Smoke Ball",        icon: "assets/items/smoke-ball.png",        effect: "Guarantees the holder can flee from wild Pokémon battles." },
  { name: "Smooth Rock",       icon: "assets/items/smooth-rock.png",       effect: "Extends the duration of Sandstorm summoned by the holder from 5 to 8 turns." },
  { name: "Sticky Barb",       icon: "assets/items/sticky-barb.png",       effect: "Damages the holder for 1/8 of its max HP at the end of each turn. Passes to a Pokémon that makes contact with the holder." },
  { name: "Terrain Extender",  icon: "assets/items/terrain-extender.png",  effect: "Extends the duration of Electric, Grassy, Misty, and Psychic Terrain set by the holder from 5 to 8 turns." },
  { name: "Throat Spray",      icon: "assets/items/throat-spray.png",      effect: "When the holder uses a sound-based move, its Special Attack is raised by 1 stage. Consumed after activation." },
  { name: "Toxic Orb",         icon: "assets/items/toxic-orb.png",         effect: "Badly poisons the holder at the end of each turn. Can be used strategically with Guts or Facade." },
  { name: "Utility Umbrella",  icon: "assets/items/utility-umbrella.png",  effect: "Protects the holder from the effects of weather, including weather damage and weather-boosted moves." },
  { name: "White Herb",        icon: "assets/items/white-herb.png",        effect: "Restores any stat that has been lowered to its original stage once. Consumed after first activation." },
  { name: "Wide Lens",         icon: "assets/items/wide-lens.png",         effect: "Increases the accuracy of the holder's moves by 10%." },
  { name: "Wise Glasses",      icon: "assets/items/wise-glasses.png",      effect: "Increases the power of the holder's special moves by 10%." },
  { name: "Zoom Lens",         icon: "assets/items/zoom-lens.png",         effect: "Increases the holder's accuracy by 20% if the holder moves after its target." },

  // ── HP-RESTORING HELD ITEMS ───────────────────────────────────────────────

  { name: "Berry Juice",  icon: "assets/items/berry-juice.png",  effect: "Restores 20 HP once when the holder's HP falls to half or below. Consumed after use." },
  { name: "Black Sludge", icon: "assets/items/black-sludge.png", effect: "Restores 1/16 of max HP each turn for Poison-type holders. Deals 1/8 max HP damage per turn to non-Poison-type holders." },
  { name: "Leftovers",    icon: "assets/items/leftovers.png",    effect: "Restores 1/16 of the holder's maximum HP at the end of each turn." },
  { name: "Shell Bell",   icon: "assets/items/shell-bell.png",   effect: "Restores HP to the holder equal to 1/8 of the damage dealt to the target by the holder's moves." },

  // ── STAT-SPECIFIC HELD ITEMS ─────────────────────────────────────────────

  { name: "Absorb Bulb",    icon: "assets/items/absorb-bulb.png",    effect: "Raises the holder's Special Attack by 1 stage when hit by a Water-type move. Consumed after activation." },
  { name: "Adrenaline Orb", icon: "assets/items/adrenaline-orb.png", effect: "Raises the holder's Speed by 1 stage when a foe uses Intimidate on it. Consumed after first activation." },
  { name: "Cell Battery",   icon: "assets/items/cell-battery.png",   effect: "Raises the holder's Attack by 1 stage when hit by an Electric-type move. Consumed after activation." },
  { name: "Deep Sea Scale", icon: "assets/items/deep-sea-scale.png", effect: "Doubles Special Defense of Clamperl when held. Also causes Clamperl to evolve into Gorebyss when traded while holding it." },
  { name: "Deep Sea Tooth", icon: "assets/items/deep-sea-tooth.png", effect: "Doubles Attack of Clamperl when held. Also causes Clamperl to evolve into Huntail when traded while holding it." },
  { name: "Eviolite",       icon: "assets/items/eviolite.png",       effect: "Raises Defense and Special Defense by 50% for Pokémon that are not fully evolved (i.e., can still evolve)." },
  { name: "Light Ball",     icon: "assets/items/light-ball.png",     effect: "Doubles both Attack and Special Attack of Pikachu. Also allows Pikachu to use Volt Tackle when bred holding it." },
  { name: "Luminous Moss",  icon: "assets/items/luminous-moss.png",  effect: "Raises the holder's Special Defense by 1 stage when hit by a Water-type move. Consumed after activation." },
  { name: "Metal Powder",   icon: "assets/items/metal-powder.png",   effect: "Doubles the Defense of Ditto when held." },
  { name: "Quick Powder",   icon: "assets/items/quick-powder.png",   effect: "Doubles the Speed of Ditto when held." },
  { name: "Snowball",       icon: "assets/items/snowball.png",       effect: "Raises the holder's Attack by 1 stage when hit by an Ice-type move. Consumed after activation." },
  { name: "Soul Dew",       icon: "assets/items/soul-dew.png",       effect: "For Latias and Latios: boosts Dragon- and Psychic-type moves by 20%. In Gen III–VI, instead raised their Sp. Atk and Sp. Def by 50%." },
  { name: "Thick Club",     icon: "assets/items/thick-club.png",     effect: "Doubles the Attack of Cubone and Marowak (including Alolan Marowak) when held." },
  { name: "Weakness Policy", icon: "assets/items/weakness-policy.png", effect: "When the holder is hit by a super-effective move, raises its Attack and Special Attack by 2 stages each. Consumed after activation." },

  // ── BERRIES ───────────────────────────────────────────────────────────────

  { name: "Aguav Berry",   icon: "assets/items/aguav-berry.png",   effect: "Restores 1/4 of max HP when HP falls to 1/4 or below. Confuses the holder if it dislikes bitter flavors (low Special Defense nature)." },
  { name: "Apicot Berry",  icon: "assets/items/apicot-berry.png",  effect: "Raises the holder's Special Defense by 1 stage when HP falls to 1/4 or below. Consumed after activation." },
  { name: "Aspear Berry",  icon: "assets/items/aspear-berry.png",  effect: "Cures the holder of the freeze status condition when consumed." },
  { name: "Babiri Berry",  icon: "assets/items/babiri-berry.png",  effect: "Halves damage taken from one super-effective Steel-type move. Consumed after activation." },
  { name: "Charti Berry",  icon: "assets/items/charti-berry.png",  effect: "Halves damage taken from one super-effective Rock-type move. Consumed after activation." },
  { name: "Cheri Berry",   icon: "assets/items/cheri-berry.png",   effect: "Cures the holder of the paralysis status condition when consumed." },
  { name: "Chesto Berry",  icon: "assets/items/chesto-berry.png",  effect: "Cures the holder of the sleep status condition when consumed." },
  { name: "Chilan Berry",  icon: "assets/items/chilan-berry.png",  effect: "Halves damage taken from one Normal-type move. Consumed after activation." },
  { name: "Chople Berry",  icon: "assets/items/chople-berry.png",  effect: "Halves damage taken from one super-effective Fighting-type move. Consumed after activation." },
  { name: "Coba Berry",    icon: "assets/items/coba-berry.png",    effect: "Halves damage taken from one super-effective Flying-type move. Consumed after activation." },
  { name: "Colbur Berry",  icon: "assets/items/colbur-berry.png",  effect: "Halves damage taken from one super-effective Dark-type move. Consumed after activation." },
  { name: "Custap Berry",  icon: "assets/items/custap-berry.png",  effect: "When HP falls to 1/4 or below, the holder moves first in its priority bracket for the next turn. Consumed after activation." },
  { name: "Enigma Berry",  icon: "assets/items/enigma-berry.png",  effect: "Restores 1/4 of max HP when the holder is hit by a super-effective move. Consumed after activation." },
  { name: "Figy Berry",    icon: "assets/items/figy-berry.png",    effect: "Restores 1/4 of max HP when HP falls to 1/4 or below. Confuses the holder if it dislikes spicy flavors (low Attack nature)." },
  { name: "Ganlon Berry",  icon: "assets/items/ganlon-berry.png",  effect: "Raises the holder's Defense by 1 stage when HP falls to 1/4 or below. Consumed after activation." },
  { name: "Haban Berry",   icon: "assets/items/haban-berry.png",   effect: "Halves damage taken from one super-effective Dragon-type move. Consumed after activation." },
  { name: "Iapapa Berry",  icon: "assets/items/iapapa-berry.png",  effect: "Restores 1/4 of max HP when HP falls to 1/4 or below. Confuses the holder if it dislikes sour flavors (low Defense nature)." },
  { name: "Jaboca Berry",  icon: "assets/items/jaboca-berry.png",  effect: "When the holder is hit by a physical move, the attacker takes damage equal to 1/8 of their max HP. Consumed after activation." },
  { name: "Kasib Berry",   icon: "assets/items/kasib-berry.png",   effect: "Halves damage taken from one super-effective Ghost-type move. Consumed after activation." },
  { name: "Kebia Berry",   icon: "assets/items/kebia-berry.png",   effect: "Halves damage taken from one super-effective Poison-type move. Consumed after activation." },
  { name: "Kee Berry",     icon: "assets/items/kee-berry.png",     effect: "Raises the holder's Defense by 1 stage when hit by a physical move. Consumed after activation." },
  { name: "Lansat Berry",  icon: "assets/items/lansat-berry.png",  effect: "Raises the holder's critical hit ratio when HP falls to 1/4 or below. Consumed after activation." },
  { name: "Liechi Berry",  icon: "assets/items/liechi-berry.png",  effect: "Raises the holder's Attack by 1 stage when HP falls to 1/4 or below. Consumed after activation." },
  { name: "Mago Berry",    icon: "assets/items/mago-berry.png",    effect: "Restores 1/4 of max HP when HP falls to 1/4 or below. Confuses the holder if it dislikes sweet flavors (low Speed nature)." },
  { name: "Maranga Berry", icon: "assets/items/maranga-berry.png", effect: "Raises the holder's Special Defense by 1 stage when hit by a special move. Consumed after activation." },
  { name: "Micle Berry",   icon: "assets/items/micle-berry.png",   effect: "Raises the accuracy of the holder's next move by 20% when HP falls to 1/4 or below. Consumed after activation." },
  { name: "Occa Berry",    icon: "assets/items/occa-berry.png",    effect: "Halves damage taken from one super-effective Fire-type move. Consumed after activation." },
  { name: "Oran Berry",    icon: "assets/items/oran-berry.png",    effect: "Restores 10 HP to the holder when HP falls to half or below. Consumed after activation." },
  { name: "Passho Berry",  icon: "assets/items/passho-berry.png",  effect: "Halves damage taken from one super-effective Water-type move. Consumed after activation." },
  { name: "Payapa Berry",  icon: "assets/items/payapa-berry.png",  effect: "Halves damage taken from one super-effective Psychic-type move. Consumed after activation." },
  { name: "Pecha Berry",   icon: "assets/items/pecha-berry.png",   effect: "Cures the holder of the poison or badly poisoned status condition when consumed." },
  { name: "Persim Berry",  icon: "assets/items/persim-berry.png",  effect: "Cures the holder of confusion when consumed." },
  { name: "Petaya Berry",  icon: "assets/items/petaya-berry.png",  effect: "Raises the holder's Special Attack by 1 stage when HP falls to 1/4 or below. Consumed after activation." },
  { name: "Rawst Berry",   icon: "assets/items/rawst-berry.png",   effect: "Cures the holder of the burn status condition when consumed." },
  { name: "Rindo Berry",   icon: "assets/items/rindo-berry.png",   effect: "Halves damage taken from one super-effective Grass-type move. Consumed after activation." },
  { name: "Roseli Berry",  icon: "assets/items/roseli-berry.png",  effect: "Halves damage taken from one super-effective Fairy-type move. Consumed after activation." },
  { name: "Rowap Berry",   icon: "assets/items/rowap-berry.png",   effect: "When the holder is hit by a special move, the attacker takes damage equal to 1/8 of their max HP. Consumed after activation." },
  { name: "Salac Berry",   icon: "assets/items/salac-berry.png",   effect: "Raises the holder's Speed by 1 stage when HP falls to 1/4 or below. Consumed after activation." },
  { name: "Shuca Berry",   icon: "assets/items/shuca-berry.png",   effect: "Halves damage taken from one super-effective Ground-type move. Consumed after activation." },
  { name: "Sitrus Berry",  icon: "assets/items/sitrus-berry.png",  effect: "Restores 1/4 of the holder's maximum HP when HP falls to half or below. Consumed after activation." },
  { name: "Starf Berry",   icon: "assets/items/starf-berry.png",   effect: "Raises a random stat by 2 stages when HP falls to 1/4 or below. Consumed after activation." },
  { name: "Tanga Berry",   icon: "assets/items/tanga-berry.png",   effect: "Halves damage taken from one super-effective Bug-type move. Consumed after activation." },
  { name: "Wacan Berry",   icon: "assets/items/wacan-berry.png",   effect: "Halves damage taken from one super-effective Electric-type move. Consumed after activation." },
  { name: "Wiki Berry",    icon: "assets/items/wiki-berry.png",    effect: "Restores 1/4 of max HP when HP falls to 1/4 or below. Confuses the holder if it dislikes dry flavors (low Special Attack nature)." },
  { name: "Yache Berry",   icon: "assets/items/yache-berry.png",   effect: "Halves damage taken from one super-effective Ice-type move. Consumed after activation." },

  // ── TYPE-ENHANCING HELD ITEMS ─────────────────────────────────────────────

  { name: "Black Belt",     icon: "assets/items/black-belt.png",     effect: "Boosts the power of the holder's Fighting-type moves by 20%." },
  { name: "Black Glasses",  icon: "assets/items/black-glasses.png",  effect: "Boosts the power of the holder's Dark-type moves by 20%." },
  { name: "Charcoal",       icon: "assets/items/charcoal.png",       effect: "Boosts the power of the holder's Fire-type moves by 20%." },
  { name: "Dragon Fang",    icon: "assets/items/dragon-fang.png",    effect: "Boosts the power of the holder's Dragon-type moves by 20%." },
  { name: "Dragon Scale",   icon: "assets/items/dragon-scale.png",   effect: "Boosts the power of the holder's Dragon-type moves by 10%. Also causes Seadra to evolve into Kingdra when traded while holding it." },
  { name: "Fairy Feather",  icon: "assets/items/fairy-feather.png",  effect: "Boosts the power of the holder's Fairy-type moves by 20%." },
  { name: "Hard Stone",     icon: "assets/items/hard-stone.png",     effect: "Boosts the power of the holder's Rock-type moves by 20%." },
  { name: "Magnet",         icon: "assets/items/magnet.png",         effect: "Boosts the power of the holder's Electric-type moves by 20%." },
  { name: "Metal Coat",     icon: "assets/items/metal-coat.png",     effect: "Boosts the power of the holder's Steel-type moves by 20%. Also evolves Onix into Steelix and Scyther into Scizor when traded while holding it." },
  { name: "Miracle Seed",   icon: "assets/items/miracle-seed.png",   effect: "Boosts the power of the holder's Grass-type moves by 20%." },
  { name: "Mystic Water",   icon: "assets/items/mystic-water.png",   effect: "Boosts the power of the holder's Water-type moves by 20%." },
  { name: "Never-Melt Ice", icon: "assets/items/never-melt-ice.png", effect: "Boosts the power of the holder's Ice-type moves by 20%." },
  { name: "Odd Incense",    icon: "assets/items/odd-incense.png",    effect: "Boosts the power of the holder's Psychic-type moves by 20%. Breeding incense for Mr. Mime." },
  { name: "Poison Barb",    icon: "assets/items/poison-barb.png",    effect: "Boosts the power of the holder's Poison-type moves by 20%." },
  { name: "Rock Incense",   icon: "assets/items/rock-incense.png",   effect: "Boosts the power of the holder's Rock-type moves by 20%. Breeding incense for Bonsly." },
  { name: "Rose Incense",   icon: "assets/items/rose-incense.png",   effect: "Boosts the power of the holder's Grass-type moves by 20%. Breeding incense for Budew." },
  { name: "Sea Incense",    icon: "assets/items/sea-incense.png",    effect: "Boosts the power of the holder's Water-type moves by 20%. Breeding incense for Azurill." },
  { name: "Sharp Beak",     icon: "assets/items/sharp-beak.png",     effect: "Boosts the power of the holder's Flying-type moves by 20%." },
  { name: "Silk Scarf",     icon: "assets/items/silk-scarf.png",     effect: "Boosts the power of the holder's Normal-type moves by 20%." },
  { name: "Silver Powder",  icon: "assets/items/silver-powder.png",  effect: "Boosts the power of the holder's Bug-type moves by 20%." },
  { name: "Soft Sand",      icon: "assets/items/soft-sand.png",      effect: "Boosts the power of the holder's Ground-type moves by 20%." },
  { name: "Spell Tag",      icon: "assets/items/spell-tag.png",      effect: "Boosts the power of the holder's Ghost-type moves by 20%." },
  { name: "Twisted Spoon",  icon: "assets/items/twisted-spoon.png",  effect: "Boosts the power of the holder's Psychic-type moves by 20%." },
  { name: "Wave Incense",   icon: "assets/items/wave-incense.png",   effect: "Boosts the power of the holder's Water-type moves by 20%. Breeding incense for Mantyke." },

  // ── PLATES (Arceus) ───────────────────────────────────────────────────────

  { name: "Draco Plate",   icon: "assets/items/draco-plate.png",   effect: "Changes Arceus to Dragon-type when held. Boosts Dragon-type moves by 20%." },
  { name: "Dread Plate",   icon: "assets/items/dread-plate.png",   effect: "Changes Arceus to Dark-type when held. Boosts Dark-type moves by 20%." },
  { name: "Earth Plate",   icon: "assets/items/earth-plate.png",   effect: "Changes Arceus to Ground-type when held. Boosts Ground-type moves by 20%." },
  { name: "Fist Plate",    icon: "assets/items/fist-plate.png",    effect: "Changes Arceus to Fighting-type when held. Boosts Fighting-type moves by 20%." },
  { name: "Flame Plate",   icon: "assets/items/flame-plate.png",   effect: "Changes Arceus to Fire-type when held. Boosts Fire-type moves by 20%." },
  { name: "Icicle Plate",  icon: "assets/items/icicle-plate.png",  effect: "Changes Arceus to Ice-type when held. Boosts Ice-type moves by 20%." },
  { name: "Insect Plate",  icon: "assets/items/insect-plate.png",  effect: "Changes Arceus to Bug-type when held. Boosts Bug-type moves by 20%." },
  { name: "Iron Plate",    icon: "assets/items/iron-plate.png",    effect: "Changes Arceus to Steel-type when held. Boosts Steel-type moves by 20%." },
  { name: "Legend Plate",  icon: "assets/items/legend-plate.png",  effect: "Allows Arceus to change to the type of the move it's using when it uses Judgment. Does not boost a specific type." },
  { name: "Meadow Plate",  icon: "assets/items/meadow-plate.png",  effect: "Changes Arceus to Grass-type when held. Boosts Grass-type moves by 20%." },
  { name: "Mind Plate",    icon: "assets/items/mind-plate.png",    effect: "Changes Arceus to Psychic-type when held. Boosts Psychic-type moves by 20%." },
  { name: "Pixie Plate",   icon: "assets/items/pixie-plate.png",   effect: "Changes Arceus to Fairy-type when held. Boosts Fairy-type moves by 20%." },
  { name: "Sky Plate",     icon: "assets/items/sky-plate.png",     effect: "Changes Arceus to Flying-type when held. Boosts Flying-type moves by 20%." },
  { name: "Splash Plate",  icon: "assets/items/splash-plate.png",  effect: "Changes Arceus to Water-type when held. Boosts Water-type moves by 20%." },
  { name: "Spooky Plate",  icon: "assets/items/spooky-plate.png",  effect: "Changes Arceus to Ghost-type when held. Boosts Ghost-type moves by 20%." },
  { name: "Stone Plate",   icon: "assets/items/stone-plate.png",   effect: "Changes Arceus to Rock-type when held. Boosts Rock-type moves by 20%." },
  { name: "Toxic Plate",   icon: "assets/items/toxic-plate.png",   effect: "Changes Arceus to Poison-type when held. Boosts Poison-type moves by 20%." },
  { name: "Zap Plate",     icon: "assets/items/zap-plate.png",     effect: "Changes Arceus to Electric-type when held. Boosts Electric-type moves by 20%." },

  // ── MEMORIES (Silvally) ───────────────────────────────────────────────────

  { name: "Bug Memory",      icon: "assets/items/bug-memory.png",      effect: "When held by Silvally, RKS System changes it to Bug-type and Techno Blast becomes Bug-type." },
  { name: "Dark Memory",     icon: "assets/items/dark-memory.png",     effect: "When held by Silvally, RKS System changes it to Dark-type and Techno Blast becomes Dark-type." },
  { name: "Dragon Memory",   icon: "assets/items/dragon-memory.png",   effect: "When held by Silvally, RKS System changes it to Dragon-type and Techno Blast becomes Dragon-type." },
  { name: "Electric Memory", icon: "assets/items/electric-memory.png", effect: "When held by Silvally, RKS System changes it to Electric-type and Techno Blast becomes Electric-type." },
  { name: "Fairy Memory",    icon: "assets/items/fairy-memory.png",    effect: "When held by Silvally, RKS System changes it to Fairy-type and Techno Blast becomes Fairy-type." },
  { name: "Fighting Memory", icon: "assets/items/fighting-memory.png", effect: "When held by Silvally, RKS System changes it to Fighting-type and Techno Blast becomes Fighting-type." },
  { name: "Fire Memory",     icon: "assets/items/fire-memory.png",     effect: "When held by Silvally, RKS System changes it to Fire-type and Techno Blast becomes Fire-type." },
  { name: "Flying Memory",   icon: "assets/items/flying-memory.png",   effect: "When held by Silvally, RKS System changes it to Flying-type and Techno Blast becomes Flying-type." },
  { name: "Ghost Memory",    icon: "assets/items/ghost-memory.png",    effect: "When held by Silvally, RKS System changes it to Ghost-type and Techno Blast becomes Ghost-type." },
  { name: "Grass Memory",    icon: "assets/items/grass-memory.png",    effect: "When held by Silvally, RKS System changes it to Grass-type and Techno Blast becomes Grass-type." },
  { name: "Ground Memory",   icon: "assets/items/ground-memory.png",   effect: "When held by Silvally, RKS System changes it to Ground-type and Techno Blast becomes Ground-type." },
  { name: "Ice Memory",      icon: "assets/items/ice-memory.png",      effect: "When held by Silvally, RKS System changes it to Ice-type and Techno Blast becomes Ice-type." },
  { name: "Poison Memory",   icon: "assets/items/poison-memory.png",   effect: "When held by Silvally, RKS System changes it to Poison-type and Techno Blast becomes Poison-type." },
  { name: "Psychic Memory",  icon: "assets/items/psychic-memory.png",  effect: "When held by Silvally, RKS System changes it to Psychic-type and Techno Blast becomes Psychic-type." },
  { name: "Rock Memory",     icon: "assets/items/rock-memory.png",     effect: "When held by Silvally, RKS System changes it to Rock-type and Techno Blast becomes Rock-type." },
  { name: "Steel Memory",    icon: "assets/items/steel-memory.png",    effect: "When held by Silvally, RKS System changes it to Steel-type and Techno Blast becomes Steel-type." },
  { name: "Water Memory",    icon: "assets/items/water-memory.png",    effect: "When held by Silvally, RKS System changes it to Water-type and Techno Blast becomes Water-type." },

  // ── GEMS ──────────────────────────────────────────────────────────────────

  { name: "Bug Gem",      icon: "assets/items/bug-gem.png",      effect: "Boosts the power of one Bug-type move used by the holder by 50%. Consumed after use." },
  { name: "Dark Gem",     icon: "assets/items/dark-gem.png",     effect: "Boosts the power of one Dark-type move used by the holder by 50%. Consumed after use." },
  { name: "Dragon Gem",   icon: "assets/items/dragon-gem.png",   effect: "Boosts the power of one Dragon-type move used by the holder by 50%. Consumed after use." },
  { name: "Electric Gem", icon: "assets/items/electric-gem.png", effect: "Boosts the power of one Electric-type move used by the holder by 50%. Consumed after use." },
  { name: "Fairy Gem",    icon: "assets/items/fairy-gem.png",    effect: "Boosts the power of one Fairy-type move used by the holder by 50%. Consumed after use." },
  { name: "Fighting Gem", icon: "assets/items/fighting-gem.png", effect: "Boosts the power of one Fighting-type move used by the holder by 50%. Consumed after use." },
  { name: "Fire Gem",     icon: "assets/items/fire-gem.png",     effect: "Boosts the power of one Fire-type move used by the holder by 50%. Consumed after use." },
  { name: "Flying Gem",   icon: "assets/items/flying-gem.png",   effect: "Boosts the power of one Flying-type move used by the holder by 50%. Consumed after use." },
  { name: "Ghost Gem",    icon: "assets/items/ghost-gem.png",    effect: "Boosts the power of one Ghost-type move used by the holder by 50%. Consumed after use." },
  { name: "Grass Gem",    icon: "assets/items/grass-gem.png",    effect: "Boosts the power of one Grass-type move used by the holder by 50%. Consumed after use." },
  { name: "Ground Gem",   icon: "assets/items/ground-gem.png",   effect: "Boosts the power of one Ground-type move used by the holder by 50%. Consumed after use." },
  { name: "Ice Gem",      icon: "assets/items/ice-gem.png",      effect: "Boosts the power of one Ice-type move used by the holder by 50%. Consumed after use." },
  { name: "Normal Gem",   icon: "assets/items/normal-gem.png",   effect: "Boosts the power of one Normal-type move used by the holder by 50%. Consumed after use." },
  { name: "Poison Gem",   icon: "assets/items/poison-gem.png",   effect: "Boosts the power of one Poison-type move used by the holder by 50%. Consumed after use." },
  { name: "Psychic Gem",  icon: "assets/items/psychic-gem.png",  effect: "Boosts the power of one Psychic-type move used by the holder by 50%. Consumed after use." },
  { name: "Rock Gem",     icon: "assets/items/rock-gem.png",     effect: "Boosts the power of one Rock-type move used by the holder by 50%. Consumed after use." },
  { name: "Steel Gem",    icon: "assets/items/steel-gem.png",    effect: "Boosts the power of one Steel-type move used by the holder by 50%. Consumed after use." },
  { name: "Water Gem",    icon: "assets/items/water-gem.png",    effect: "Boosts the power of one Water-type move used by the holder by 50%. Consumed after use." },

  // ── DRIVES (Genesect) ─────────────────────────────────────────────────────

  { name: "Burn Drive",  icon: "assets/items/burn-drive.png",  effect: "When held by Genesect, changes Techno Blast to Fire-type and changes Genesect's coloration." },
  { name: "Chill Drive", icon: "assets/items/chill-drive.png", effect: "When held by Genesect, changes Techno Blast to Ice-type and changes Genesect's coloration." },
  { name: "Douse Drive", icon: "assets/items/douse-drive.png", effect: "When held by Genesect, changes Techno Blast to Water-type and changes Genesect's coloration." },
  { name: "Shock Drive", icon: "assets/items/shock-drive.png", effect: "When held by Genesect, changes Techno Blast to Electric-type and changes Genesect's coloration." },

  // ── FORM-CHANGING ITEMS ───────────────────────────────────────────────────

  { name: "Adamant Crystal",   icon: "assets/items/adamant-crystal.png",   effect: "When held by Dialga, it shifts to its Origin Forme and its signature move Steel Temporal is powered up." },
  { name: "Blue Orb",          icon: "assets/items/blue-orb.png",          effect: "When held by Kyogre, triggers Primal Reversion, transforming it into Primal Kyogre with greatly increased stats." },
  { name: "Cornerstone Mask",  icon: "assets/items/cornerstone-mask.png",  effect: "When held by Ogerpon, it takes on Cornerstone Mask Forme and becomes Rock-type." },
  { name: "Griseous Core",     icon: "assets/items/griseous-core.png",     effect: "When held by Giratina, it shifts to Origin Forme. Boosts Ghost- and Dragon-type moves by 20%. Upgraded form of the Griseous Orb." },
  { name: "Griseous Orb",      icon: "assets/items/griseous-orb.png",      effect: "When held by Giratina outside its home dimension, shifts it to Origin Forme. Boosts Ghost- and Dragon-type moves by 20%." },
  { name: "Hearthflame Mask",  icon: "assets/items/hearthflame-mask.png",  effect: "When held by Ogerpon, it takes on Hearthflame Mask Forme and becomes Fire-type." },
  { name: "Lustrous Globe",    icon: "assets/items/lustrous-globe.png",    effect: "When held by Palkia, it shifts to its Origin Forme and its signature move Spacial Rend is powered up." },
  { name: "Red Orb",           icon: "assets/items/red-orb.png",           effect: "When held by Groudon, triggers Primal Reversion, transforming it into Primal Groudon with greatly increased stats." },
  { name: "Rusted Shield",     icon: "assets/items/rusted-shield.png",     effect: "When held by Zamazenta, transforms it into Crowned Shield Forme with a 720 BST and access to Behemoth Bash." },
  { name: "Rusted Sword",      icon: "assets/items/rusted-sword.png",      effect: "When held by Zacian, transforms it into Crowned Sword Forme with a 720 BST and access to Behemoth Blade." },
  { name: "Wellspring Mask",   icon: "assets/items/wellspring-mask.png",   effect: "When held by Ogerpon, it takes on Wellspring Mask Forme and becomes Water-type." },

  // ── MEGA STONES ───────────────────────────────────────────────────────────

  { name: "Abomasite",     icon: "assets/items/abomasite.png",     effect: "Mega Evolves Abomasnow into Mega Abomasnow when held." },
  { name: "Absolite",      icon: "assets/items/absolite.png",      effect: "Mega Evolves Absol into Mega Absol when held." },
  { name: "Absolite Z",    icon: "assets/items/absolite-z.png",    effect: "Mega Evolves Absol into Mega Absol Z when held." },
  { name: "Aerodactylite", icon: "assets/items/aerodactylite.png", effect: "Mega Evolves Aerodactyl into Mega Aerodactyl when held." },
  { name: "Aggronite",     icon: "assets/items/aggronite.png",     effect: "Mega Evolves Aggron into Mega Aggron when held." },
  { name: "Alakazite",     icon: "assets/items/alakazite.png",     effect: "Mega Evolves Alakazam into Mega Alakazam when held." },
  { name: "Altarianite",   icon: "assets/items/altarianite.png",   effect: "Mega Evolves Altaria into Mega Altaria when held." },
  { name: "Ampharosite",   icon: "assets/items/ampharosite.png",   effect: "Mega Evolves Ampharos into Mega Ampharos when held." },
  { name: "Audinite",      icon: "assets/items/audinite.png",      effect: "Mega Evolves Audino into Mega Audino when held." },
  { name: "Banettite",     icon: "assets/items/banettite.png",     effect: "Mega Evolves Banette into Mega Banette when held." },
  { name: "Barbaracite",   icon: "assets/items/barbaracite.png",   effect: "Mega Evolves Barbaracle into Mega Barbaracle when held." },
  { name: "Baxcalibrite",  icon: "assets/items/baxcalibrite.png",  effect: "Mega Evolves Baxcalibur into Mega Baxcalibur when held." },
  { name: "Beedrillite",   icon: "assets/items/beedrillite.png",   effect: "Mega Evolves Beedrill into Mega Beedrill when held." },
  { name: "Blastoisinite", icon: "assets/items/blastoisinite.png", effect: "Mega Evolves Blastoise into Mega Blastoise when held." },
  { name: "Blazikenite",   icon: "assets/items/blazikenite.png",   effect: "Mega Evolves Blaziken into Mega Blaziken when held." },
  { name: "Cameruptite",   icon: "assets/items/cameruptite.png",   effect: "Mega Evolves Camerupt into Mega Camerupt when held." },
  { name: "Chandelurite",  icon: "assets/items/chandelurite.png",  effect: "Mega Evolves Chandelure into Mega Chandelure when held." },
  { name: "Charizardite X", icon: "assets/items/charizardite-x.png", effect: "Mega Evolves Charizard into Mega Charizard X when held." },
  { name: "Charizardite Y", icon: "assets/items/charizardite-y.png", effect: "Mega Evolves Charizard into Mega Charizard Y when held." },
  { name: "Chesnaughtite", icon: "assets/items/chesnaughtite.png", effect: "Mega Evolves Chesnaught into Mega Chesnaught when held." },
  { name: "Chimechite",    icon: "assets/items/chimechite.png",    effect: "Mega Evolves Chimecho into Mega Chimecho when held." },
  { name: "Clefablite",    icon: "assets/items/clefablite.png",    effect: "Mega Evolves Clefable into Mega Clefable when held." },
  { name: "Crabominite",   icon: "assets/items/crabominite.png",   effect: "Mega Evolves Crabominable into Mega Crabominable when held." },
  { name: "Darkranite",    icon: "assets/items/darkranite.png",    effect: "Mega Evolves Darkrai into Mega Darkrai when held." },
  { name: "Delphoxite",    icon: "assets/items/delphoxite.png",    effect: "Mega Evolves Delphox into Mega Delphox when held." },
  { name: "Diancite",      icon: "assets/items/diancite.png",      effect: "Mega Evolves Diancie into Mega Diancie when held." },
  { name: "Dragalgite",    icon: "assets/items/dragalgite.png",    effect: "Mega Evolves Dragalge into Mega Dragalge when held." },
  { name: "Dragoninite",   icon: "assets/items/dragoninite.png",   effect: "Mega Evolves Dragonite into Mega Dragonite when held." },
  { name: "Drampanite",    icon: "assets/items/drampanite.png",    effect: "Mega Evolves Drampa into Mega Drampa when held." },
  { name: "Eelektrossite", icon: "assets/items/eelektrossite.png", effect: "Mega Evolves Eelektross into Mega Eelektross when held." },
  { name: "Emboarite",     icon: "assets/items/emboarite.png",     effect: "Mega Evolves Emboar into Mega Emboar when held." },
  { name: "Excadrite",     icon: "assets/items/excadrite.png",     effect: "Mega Evolves Excadrill into Mega Excadrill when held." },
  { name: "Falinksite",    icon: "assets/items/falinksite.png",    effect: "Mega Evolves Falinks into Mega Falinks when held." },
  { name: "Feraligite",    icon: "assets/items/feraligite.png",    effect: "Mega Evolves Feraligatr into Mega Feraligatr when held." },
  { name: "Floettite",     icon: "assets/items/floettite.png",     effect: "Mega Evolves Floette into Mega Floette when held." },
  { name: "Froslassite",   icon: "assets/items/froslassite.png",   effect: "Mega Evolves Froslass into Mega Froslass when held." },
  { name: "Galladite",     icon: "assets/items/galladite.png",     effect: "Mega Evolves Gallade into Mega Gallade when held." },
  { name: "Garchompite",   icon: "assets/items/garchompite.png",   effect: "Mega Evolves Garchomp into Mega Garchomp when held." },
  { name: "Garchompite Z", icon: "assets/items/garchompite-z.png", effect: "Mega Evolves Garchomp into an alternate Mega Garchomp Z when held." },
  { name: "Gardevoirite",  icon: "assets/items/gardevoirite.png",  effect: "Mega Evolves Gardevoir into Mega Gardevoir when held." },
  { name: "Gengarite",     icon: "assets/items/gengarite.png",     effect: "Mega Evolves Gengar into Mega Gengar when held." },
  { name: "Glalitite",     icon: "assets/items/glalitite.png",     effect: "Mega Evolves Glalie into Mega Glalie when held." },
  { name: "Glimmoranite",  icon: "assets/items/glimmoranite.png",  effect: "Mega Evolves Glimmora into Mega Glimmora when held." },
  { name: "Golisopite",    icon: "assets/items/golisopite.png",    effect: "Mega Evolves Golisopod into Mega Golisopod when held." },
  { name: "Golurkite",     icon: "assets/items/golurkite.png",     effect: "Mega Evolves Golurk into Mega Golurk when held." },
  { name: "Greninjite",    icon: "assets/items/greninjite.png",    effect: "Mega Evolves Greninja into Mega Greninja when held." },
  { name: "Gyaradosite",   icon: "assets/items/gyaradosite.png",   effect: "Mega Evolves Gyarados into Mega Gyarados when held." },
  { name: "Hawluchanite",  icon: "assets/items/hawluchanite.png",  effect: "Mega Evolves Hawlucha into Mega Hawlucha when held." },
  { name: "Heatranite",    icon: "assets/items/heatranite.png",    effect: "Mega Evolves Heatran into Mega Heatran when held." },
  { name: "Heracronite",   icon: "assets/items/heracronite.png",   effect: "Mega Evolves Heracross into Mega Heracross when held." },
  { name: "Houndoominite", icon: "assets/items/houndoominite.png", effect: "Mega Evolves Houndoom into Mega Houndoom when held." },
  { name: "Kangaskhanite", icon: "assets/items/kangaskhanite.png", effect: "Mega Evolves Kangaskhan into Mega Kangaskhan when held." },
  { name: "Latiasite",     icon: "assets/items/latiasite.png",     effect: "Mega Evolves Latias into Mega Latias when held." },
  { name: "Latiosite",     icon: "assets/items/latiosite.png",     effect: "Mega Evolves Latios into Mega Latios when held." },
  { name: "Lopunnite",     icon: "assets/items/lopunnite.png",     effect: "Mega Evolves Lopunny into Mega Lopunny when held." },
  { name: "Lucarionite",   icon: "assets/items/lucarionite.png",   effect: "Mega Evolves Lucario into Mega Lucario when held." },
  { name: "Lucarionite Z", icon: "assets/items/lucarionite-z.png", effect: "Mega Evolves Lucario into an alternate Mega Lucario Z when held." },
  { name: "Magearnite",    icon: "assets/items/magearnite.png",    effect: "Mega Evolves Magearna into Mega Magearna when held." },
  { name: "Malamarite",    icon: "assets/items/malamarite.png",    effect: "Mega Evolves Malamar into Mega Malamar when held." },
  { name: "Manectite",     icon: "assets/items/manectite.png",     effect: "Mega Evolves Manectric into Mega Manectric when held." },
  { name: "Mawilite",      icon: "assets/items/mawilite.png",      effect: "Mega Evolves Mawile into Mega Mawile when held." },
  { name: "Medichamite",   icon: "assets/items/medichamite.png",   effect: "Mega Evolves Medicham into Mega Medicham when held." },
  { name: "Meganiumite",   icon: "assets/items/meganiumite.png",   effect: "Mega Evolves Meganium into Mega Meganium when held." },
  { name: "Meowsticite",   icon: "assets/items/meowsticite.png",   effect: "Mega Evolves Meowstic into Mega Meowstic when held." },
  { name: "Metagrossite",  icon: "assets/items/metagrossite.png",  effect: "Mega Evolves Metagross into Mega Metagross when held." },
  { name: "Mewtwonite X",  icon: "assets/items/mewtwonite-x.png",  effect: "Mega Evolves Mewtwo into Mega Mewtwo X when held." },
  { name: "Mewtwonite Y",  icon: "assets/items/mewtwonite-y.png",  effect: "Mega Evolves Mewtwo into Mega Mewtwo Y when held." },
  { name: "Pidgeotite",    icon: "assets/items/pidgeotite.png",    effect: "Mega Evolves Pidgeot into Mega Pidgeot when held." },
  { name: "Pinsirite",     icon: "assets/items/pinsirite.png",     effect: "Mega Evolves Pinsir into Mega Pinsir when held." },
  { name: "Pyroarite",     icon: "assets/items/pyroarite.png",     effect: "Mega Evolves Pyroar into Mega Pyroar when held." },
  { name: "Raichunite X",  icon: "assets/items/raichunite-x.png",  effect: "Mega Evolves Raichu into Mega Raichu X when held." },
  { name: "Raichunite Y",  icon: "assets/items/raichunite-y.png",  effect: "Mega Evolves Raichu into Mega Raichu Y when held." },
  { name: "Sablenite",     icon: "assets/items/sablenite.png",     effect: "Mega Evolves Sableye into Mega Sableye when held." },
  { name: "Salamencite",   icon: "assets/items/salamencite.png",   effect: "Mega Evolves Salamence into Mega Salamence when held." },
  { name: "Sceptilite",    icon: "assets/items/sceptilite.png",    effect: "Mega Evolves Sceptile into Mega Sceptile when held." },
  { name: "Scizorite",     icon: "assets/items/scizorite.png",     effect: "Mega Evolves Scizor into Mega Scizor when held." },
  { name: "Scolipite",     icon: "assets/items/scolipite.png",     effect: "Mega Evolves Scolipede into Mega Scolipede when held." },
  { name: "Scovillainite", icon: "assets/items/scovillainite.png", effect: "Mega Evolves Scovillain into Mega Scovillain when held." },
  { name: "Scraftinite",   icon: "assets/items/scraftinite.png",   effect: "Mega Evolves Scrafty into Mega Scrafty when held." },
  { name: "Sharpedonite",  icon: "assets/items/sharpedonite.png",  effect: "Mega Evolves Sharpedo into Mega Sharpedo when held." },
  { name: "Skarmorite",    icon: "assets/items/skarmorite.png",    effect: "Mega Evolves Skarmory into Mega Skarmory when held." },
  { name: "Slowbronite",   icon: "assets/items/slowbronite.png",   effect: "Mega Evolves Slowbro into Mega Slowbro when held." },
  { name: "Staraptite",    icon: "assets/items/staraptite.png",    effect: "Mega Evolves Staraptor into Mega Staraptor when held." },
  { name: "Starminite",    icon: "assets/items/starminite.png",    effect: "Mega Evolves Starmie into Mega Starmie when held." },
  { name: "Steelixite",    icon: "assets/items/steelixite.png",    effect: "Mega Evolves Steelix into Mega Steelix when held." },
  { name: "Swampertite",   icon: "assets/items/swampertite.png",   effect: "Mega Evolves Swampert into Mega Swampert when held." },
  { name: "Tatsugirinite", icon: "assets/items/tatsugirinite.png", effect: "Mega Evolves Tatsugiri into Mega Tatsugiri when held." },
  { name: "Tyranitarite",  icon: "assets/items/tyranitarite.png",  effect: "Mega Evolves Tyranitar into Mega Tyranitar when held." },
  { name: "Venusaurite",   icon: "assets/items/venusaurite.png",   effect: "Mega Evolves Venusaur into Mega Venusaur when held." },
  { name: "Victreebelite", icon: "assets/items/victreebelite.png", effect: "Mega Evolves Victreebel into Mega Victreebel when held." },
  { name: "Zeraorite",     icon: "assets/items/zeraorite.png",     effect: "Mega Evolves Zeraora into Mega Zeraora when held." },
  { name: "Zygardite",     icon: "assets/items/zygardite.png",     effect: "Mega Evolves Zygarde into Mega Zygarde when held." },

];