window.pokemonData = [
    {
      number: 1,
      name: 'Bulbasaur',
      available: true,
      types: ['Grass', 'Poison'],
      ability: 'Overgrow',
      hiddenAbility: 'Chlorophyll',
      aiAbility: '',
      gender: '87.5% male, 12.5% female',
      catchRate: 45,
      stats: {
        hp: 45,
        atk: 49,
        def: 49,
        spa: 65,
        spd: 65,
        spe: 45
      },
      evolution: ['Bulbasaur', 'Ivysaur', 'Venusaur'],
      learnset: [
        { level: 1,  move: 'Tackle'      },
        { level: 1,  move: 'Growl'       },
        { level: 3,  move: 'Vine Whip'   },
        { level: 5,  move: 'Acid'        },
        { level: 8,  move: 'Headbutt'    },
        { level: 11, move: 'Growth'      },
        { level: 14, move: 'Poison Powder' },
        { level: 14, move: 'Sleep Powder'  },
        { level: 15, move: 'Razor Leaf'    },
        { level: 17, move: 'Take Down'     },
        { level: 20, move: 'Magical Leaf'  },
        { level: 22, move: 'Sludge Bomb'   },
        { level: 26, move: 'Seed Bomb'     },
        { level: 30, move: 'Toxic'         },
        { level: 30, move: 'Double-Edge'   },
        { level: 36, move: 'Leaf Blade'    },
        { level: 48, move: 'Giga Drain'    }
      ]
    },
    // more entries start here
    {
        number: 2,
        name: 'Ivysaur',
        available: true,
        types: ['Grass', 'Poison'],
        ability: 'Overgrow',
        hiddenAbility: 'Chlorophyll',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 60,
          atk: 62,
          def: 63,
          spa: 80,
          spd: 80,
          spe: 60
        },
        evolution: ['Bulbasaur', 'Ivysaur', 'Venusaur'],
        learnset: [
          { level: 1,  move: 'Tackle'      },
          { level: 1,  move: 'Growl'       },
          { level: 3,  move: 'Vine Whip'   },
          { level: 5,  move: 'Acid'        },
          { level: 8,  move: 'Headbutt'    },
          { level: 12, move: 'Poison Powder' },
          { level: 15, move: 'Sleep Powder'  },
          { level: 16, move: 'Mega Drain'    },
          { level: 19, move: 'Take Down'     },
          { level: 22, move: 'Magical Leaf'  },
          { level: 25, move: 'Sludge Bomb'   },
          { level: 28, move: 'Seed Bomb'     },
          { level: 31, move: 'Toxic'         },
          { level: 33, move: 'Double-Edge'   },
          { level: 55, move: 'Giga Drain'    }
        ]
      },
      {
        number: 3,
        name: 'Venusaur',
        available: true,
        types: ['Grass', 'Poison'],
        ability: 'Overgrow',
        hiddenAbility: 'Chlorophyll',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 80,
          atk: 82,
          def: 83,
          spa: 100,
          spd: 100,
          spe: 80
        },
        evolution: ['Bulbasaur', 'Ivysaur', 'Venusaur'],
        learnset: [
          { level: 1,  move: 'Giga Drain'     },
          { level: 1,  move: 'Ancient Power'  },
          { level: 1,  move: 'Tackle'         },
          { level: 1,  move: 'Growl'          },
          { level: 3,  move: 'Vine Whip'      },
          { level: 5,  move: 'Acid'           },
          { level: 8,  move: 'Headbutt'       },
          { level: 12, move: 'Poison Powder'  },
          { level: 15, move: 'Sleep Powder'   },
          { level: 18, move: 'Mega Drain'     },
          { level: 21, move: 'Take Down'      },
          { level: 25, move: 'Magical Leaf'   },
          { level: 28, move: 'Sludge Bomb'    },
          { level: 32, move: 'Seed Bomb'      },
          { level: 35, move: 'Toxic'          },
          { level: 36, move: 'Leaf Blade'     },
          { level: 40, move: 'Double-Edge'    },
          { level: 45, move: 'Earth Power'    }
        ]
      },
      {
        number: 3,
        name: 'Mega Venusaur',
        available: true,
        types: ['Grass', 'Poison'],
        ability: 'Thick Fat',
        hiddenAbility: '',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 80,
          atk: 100,
          def: 123,
          spa: 122,
          spd: 120,
          spe: 80
        },
        evolution: '',
        learnset: [
          { level: 1,  move: 'Giga Drain'     },
          { level: 1,  move: 'Ancient Power'  },
          { level: 1,  move: 'Tackle'         },
          { level: 1,  move: 'Growl'          },
          { level: 3,  move: 'Vine Whip'      },
          { level: 5,  move: 'Acid'           },
          { level: 8,  move: 'Headbutt'       },
          { level: 12, move: 'Poison Powder'  },
          { level: 15, move: 'Sleep Powder'   },
          { level: 18, move: 'Mega Drain'     },
          { level: 21, move: 'Take Down'      },
          { level: 25, move: 'Magical Leaf'   },
          { level: 28, move: 'Sludge Bomb'    },
          { level: 32, move: 'Seed Bomb'      },
          { level: 35, move: 'Toxic'          },
          { level: 36, move: 'Leaf Blade'     },
          { level: 40, move: 'Double-Edge'    },
          { level: 45, move: 'Earth Power'    }
        ]
      },
      {
        number: 4,
        name: 'Charmander',
        available: true,
        types: 'Fire',
        ability: 'Blaze',
        hiddenAbility: 'Solar Power',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 39,
          atk: 52,
          def: 43,
          spa: 60,
          spd: 50,
          spe: 65
        },
        evolution: ['Charmander', 'Charmeleon', 'Charizard'],
        learnset: [
          { level: 1,  move: 'Scratch'        },
          { level: 1,  move: 'Growl'          },
          { level: 5,  move: 'Ember'          },
          { level: 8,  move: 'Smokescreen'    },
          { level: 11, move: 'Bite'          },
          { level: 14, move: 'Dragon Breath' },
          { level: 16, move: 'Fire Fang'     },
          { level: 20, move: 'Slash'          },
          { level: 25, move: 'Flame Burst'    },
          { level: 29, move: 'Dig'            },
          { level: 32, move: 'Flamethrower'   },
          { level: 36, move: 'Brick Break'    },
          { level: 40, move: 'Heat Wave'      },
          { level: 48, move: 'Flare Blitz'    }
        ]
      },
      {
        number: 5,
        name: 'Charmeleon',
        available: true,
        types: 'Fire',
        ability: 'Blaze',
        hiddenAbility: 'Solar Power',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 58,
          atk: 64,
          def: 58,
          spa: 80,
          spd: 65,
          spe: 80
        },
        evolution: ['Charmander', 'Charmeleon', 'Charizard'],
        learnset: [
          { level: 1,  move: 'Scratch'        },
          { level: 1,  move: 'Growl'          },
          { level: 5,  move: 'Ember'          },
          { level: 8,  move: 'Smokescreen'    },
          { level: 11, move: 'Bite'           },
          { level: 14, move: 'Dragon Breath'  },
          { level: 16, move: 'Fire Fang'      },
          { level: 16, move: 'Metal Claw'     },
          { level: 20, move: 'Slash'          },
          { level: 25, move: 'Flame Burst'    },
          { level: 28, move: 'Dig'            },
          { level: 33, move: 'Dragon Claw'    },
          { level: 36, move: 'Flamethrower'   },
          { level: 36, move: 'Brick Break'    },
          { level: 40, move: 'Heat Wave'      },
          { level: 48, move: 'Flare Blitz'    }
        ]
      },
      {
        number: 6,
        name: 'Charizard',
        available: true,
        types: ['Fire', 'Flying'],
        ability: 'Blaze',
        hiddenAbility: 'Solar Power',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 78,
          atk: 84,
          def: 78,
          spa: 109,
          spd: 85,
          spe: 100
        },
        evolution: ['Charmander', 'Charmeleon', 'Charizard'],
        learnset: [
          { level: 1,  move: 'Shadow Claw'    },
          { level: 1,  move: 'Hurricane'      },
          { level: 1,  move: 'Dragon Rush'    },
          { level: 1,  move: 'Scratch'        },
          { level: 1,  move: 'Growl'          },
          { level: 5,  move: 'Ember'          },
          { level: 8,  move: 'Smokescreen'    },
          { level: 11, move: 'Bite'           },
          { level: 14, move: 'Dragon Breath'  },
          { level: 16, move: 'Fire Fang'      },
          { level: 16, move: 'Metal Claw'     },
          { level: 20, move: 'Slash'          },
          { level: 25, move: 'Flame Burst'    },
          { level: 28, move: 'Dig'            },
          { level: 33, move: 'Dual Chop'      },
          { level: 36, move: 'Air Slash'      },
          { level: 41, move: 'Crunch'         },
          { level: 47, move: 'Dragon Claw'    },
          { level: 52, move: 'Heat Wave'      },
          { level: 57, move: 'Dual Wingbeat'  },
          { level: 62, move: 'Flare Blitz'    }
        ]
      },
      {
        number: 6,
        name: 'Mega Charizard X',
        available: true,
        types: ['Fire', 'Dragon'],
        ability: 'Tough Claws',
        hiddenAbility: '',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 78,
          atk: 130,
          def: 111,
          spa: 130,
          spd: 85,
          spe: 100
        },
        evolution: '',
        learnset: [
          { level: 1,  move: 'Shadow Claw'    },
          { level: 1,  move: 'Hurricane'      },
          { level: 1,  move: 'Dragon Rush'    },
          { level: 1,  move: 'Scratch'        },
          { level: 1,  move: 'Growl'          },
          { level: 5,  move: 'Ember'          },
          { level: 8,  move: 'Smokescreen'    },
          { level: 11, move: 'Bite'           },
          { level: 14, move: 'Dragon Breath'  },
          { level: 16, move: 'Fire Fang'      },
          { level: 16, move: 'Metal Claw'     },
          { level: 20, move: 'Slash'          },
          { level: 25, move: 'Flame Burst'    },
          { level: 28, move: 'Dig'            },
          { level: 33, move: 'Dual Chop'      },
          { level: 36, move: 'Air Slash'      },
          { level: 41, move: 'Crunch'         },
          { level: 47, move: 'Dragon Claw'    },
          { level: 52, move: 'Heat Wave'      },
          { level: 57, move: 'Dual Wingbeat'  },
          { level: 62, move: 'Flare Blitz'    }
        ]
      },
      {
        number: 6,
        name: 'Mega Charizard Y',
        available: true,
        types: ['Fire', 'Flying'],
        ability: 'Solar Power',
        hiddenAbility: '',
        aiAbility: 'Drought',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 78,
          atk: 104,
          def: 78,
          spa: 159,
          spd: 115,
          spe: 100
        },
        evolution: '',
        learnset: [
          { level: 1,  move: 'Shadow Claw'    },
          { level: 1,  move: 'Hurricane'      },
          { level: 1,  move: 'Dragon Rush'    },
          { level: 1,  move: 'Scratch'        },
          { level: 1,  move: 'Growl'          },
          { level: 5,  move: 'Ember'          },
          { level: 8,  move: 'Smokescreen'    },
          { level: 11, move: 'Bite'           },
          { level: 14, move: 'Dragon Breath'  },
          { level: 16, move: 'Fire Fang'      },
          { level: 16, move: 'Metal Claw'     },
          { level: 20, move: 'Slash'          },
          { level: 25, move: 'Flame Burst'    },
          { level: 28, move: 'Dig'            },
          { level: 33, move: 'Dual Chop'      },
          { level: 36, move: 'Air Slash'      },
          { level: 41, move: 'Crunch'         },
          { level: 47, move: 'Dragon Claw'    },
          { level: 52, move: 'Heat Wave'      },
          { level: 57, move: 'Dual Wingbeat'  },
          { level: 62, move: 'Flare Blitz'    }
        ]
      },
      {
        number: 7,
        name: 'Squirtle',
        available: true,
        types: ['Water'],
        ability: 'Torrent',
        hiddenAbility: 'Rain Dish',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 44,
          atk: 48,
          def: 65,
          spa: 50,
          spd: 64,
          spe: 43
        },
        evolution: ['Squirtle', 'Wartortle', 'Blastoise'],
        learnset: [
          { level: 1,  move: 'Tackle'        },
          { level: 4,  move: 'Water Gun'     },
          { level: 4,  move: 'Tail Whip'     },
          { level: 9,  move: 'Bite'          },
          { level: 13, move: 'Bubblebeam'    },
          { level: 16, move: 'Aurora Beam'   },
          { level: 20, move: 'Aqua Jet'      },
          { level: 24, move: 'Aqua Tail'     },
          { level: 26, move: 'Yawn'          },
          { level: 29, move: 'Body Slam'     },
          { level: 32, move: 'Ice Punch'     },
          { level: 38, move: 'Wave Crash'    },
          { level: 43, move: 'Mirror Coat'   },
          { level: 49, move: 'Water Spout'   }
        ]
      },
      {
        number: 8,
        name: 'Wartortle',
        available: true,
        types: ['Water'],
        ability: 'Torrent',
        hiddenAbility: 'Rain Dish',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 59,
          atk: 63,
          def: 80,
          spa: 65,
          spd: 80,
          spe: 58
        },
        evolution: ['Squirtle', 'Wartortle', 'Blastoise'],
        learnset: [
          { level: 1,  move: 'Tackle'        },
          { level: 4,  move: 'Water Gun'     },
          { level: 4,  move: 'Tail Whip'     },
          { level: 9,  move: 'Bite'          },
          { level: 13, move: 'Bubblebeam'    },
          { level: 16, move: 'Aurora Beam'   },
          { level: 22, move: 'Aqua Jet'      },
          { level: 26, move: 'Aqua Tail'     },
          { level: 29, move: 'Yawn'          },
          { level: 32, move: 'Body Slam'     },
          { level: 36, move: 'Brick Break'   },
          { level: 39, move: 'Ice Punch'     },
          { level: 44, move: 'Wave Crash'    },
          { level: 50, move: 'Mirror Coat'   },
          { level: 57, move: 'Water Spout'   }
        ]
      },
      {
        number: 9,
        name: 'Blastoise',
        available: true,
        types: ['Water'],
        ability: 'Torrent',
        hiddenAbility: 'Rain Dish',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 79,
          atk: 83,
          def: 100,
          spa: 85,
          spd: 105,
          spe: 78
        },
        evolution: ['Squirtle', 'Wartortle', 'Blastoise'],
        learnset: [
          { level: 1,  move: 'Water Spout'   },
          { level: 1,  move: 'Water Pulse'   },
          { level: 1,  move: 'Aura Sphere'   },
          { level: 1,  move: 'Mirror Coat'   },
          { level: 1,  move: 'Fake Out'      },
          { level: 1,  move: 'Muddy Water'   },
          { level: 1,  move: 'Tackle'        },
          { level: 4,  move: 'Water Gun'     },
          { level: 4,  move: 'Tail Whip'     },
          { level: 9,  move: 'Bite'          },
          { level: 13, move: 'Bubblebeam'    },
          { level: 16, move: 'Aurora Beam'   },
          { level: 22, move: 'Aqua Jet'      },
          { level: 29, move: 'Aqua Tail'     },
          { level: 33, move: 'Yawn'          },
          { level: 37, move: 'Body Slam'     },
          { level: 40, move: 'Brick Break'   },
          { level: 42, move: 'Ice Punch'     },
          { level: 45, move: 'Double-Edge'   },
          { level: 50, move: 'Wave Crash'    }
        ]
      },
      {
        number: 9,
        name: 'Mega Blastoise',
        available: true,
        types: ['Water'],
        ability: 'Mega Launcher',
        hiddenAbility: '',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        stats: {
          hp: 79,
          atk: 103,
          def: 120,
          spa: 135,
          spd: 115,
          spe: 78
        },
        evolution: '',
        learnset: [
          { level: 1,  move: 'Water Spout'   },
          { level: 1,  move: 'Water Pulse'   },
          { level: 1,  move: 'Aura Sphere'   },
          { level: 1,  move: 'Mirror Coat'   },
          { level: 1,  move: 'Fake Out'      },
          { level: 1,  move: 'Muddy Water'   },
          { level: 1,  move: 'Tackle'        },
          { level: 4,  move: 'Water Gun'     },
          { level: 4,  move: 'Tail Whip'     },
          { level: 9,  move: 'Bite'          },
          { level: 13, move: 'Bubblebeam'    },
          { level: 16, move: 'Aurora Beam'   },
          { level: 22, move: 'Aqua Jet'      },
          { level: 29, move: 'Aqua Tail'     },
          { level: 33, move: 'Yawn'          },
          { level: 37, move: 'Body Slam'     },
          { level: 40, move: 'Brick Break'   },
          { level: 42, move: 'Ice Punch'     },
          { level: 45, move: 'Double-Edge'   },
          { level: 50, move: 'Wave Crash'    }
        ]
      },
      {
        number: 10,
        name: 'Caterpie',
        available: false,
        types: ['Bug'],
        ability: 'Shield Dust',
        hiddenAbility: 'Run Away',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 255,
        stats: {
          hp: 45,
          atk: 30,
          def: 35,
          spa: 20,
          spd: 20,
          spe: 45
        },
        evolution: ['Caterpie', 'Metapod', 'Butterfree'],
        learnset: [
          { level: 1, move: 'Tackle'     },
          { level: 1, move: 'String Shot' },
          { level: 9, move: 'Bug Bite'   }
        ]
      },
      {
        number: 11,
        name: 'Metapod',
        available: false,
        types: ['Bug'],
        ability: 'Shed Skin',
        hiddenAbility: '',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 120,
        stats: {
          hp: 50,
          atk: 20,
          def: 55,
          spa: 25,
          spd: 25,
          spe: 30
        },
        evolution: ['Caterpie', 'Metapod', 'Butterfree'],
        learnset: [
          { level: 1, move: 'Tackle' },
          { level: 7, move: 'Harden' }
        ]
      },
      {
        number: 12,
        name: 'Butterfree',
        available: false,
        types: ['Bug', 'Flying'],
        ability: 'Compound Eyes',
        hiddenAbility: 'Tinted Lens',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 45,
        heldItem: {name: "Silver Powder", rate: 5},
        stats: {
          hp: 60,
          atk: 45,
          def: 50,
          spa: 90,
          spd: 80,
          spe: 70
        },
        evolution: ['Caterpie', 'Metapod', 'Butterfree'],
        learnset: [
          { level: 1,  move: 'Rage Powder' },
          { level: 1,  move: 'Pollen Puff' },
          { level: 1,  move: 'Harden'      },
          { level: 1,  move: 'Tackle'      },
          { level: 1,  move: 'String Shot' },
          { level: 1,  move: 'Bug Bite'    },
          { level: 1,  move: 'Confusion'   },
          { level: 10, move: 'Confusion'   },
          { level: 10, move: 'Mega Drain'  },
          { level: 12, move: 'Supersonic'  },
          { level: 13, move: 'Poison Powder' },
          { level: 13, move: 'Stun Spore'    },
          { level: 15, move: 'Sleep Powder'  },
          { level: 16, move: 'Psybeam'     },
          { level: 19, move: 'Silver Wind' },
          { level: 22, move: 'Safeguard'   },
          { level: 24, move: 'U-turn'      },
          { level: 28, move: 'Air Slash'   },
          { level: 31, move: 'Giga Drain'  },
          { level: 34, move: 'Bug Buzz'    },
          { level: 38, move: 'Hurricane'   },
          { level: 42, move: 'Tailwind'    }
        ]
      },
      {
        number: 13,
        name: 'Weedle',
        available: true,
        types: ['Bug', 'Poison'],
        ability: 'Shield Dust',
        hiddenAbility: 'Run Away',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 255,
        stats: {
          hp: 40,
          atk: 35,
          def: 30,
          spa: 20,
          spd: 20,
          spe: 50
        },
        evolution: ['Weedle', 'Kakuna', 'Beedrill'],
        learnset: [
          { level: 1, move: 'Poison Sting' },
          { level: 1, move: 'String Shot'  },
          { level: 9, move: 'Bug Bite'     }
        ]
      },
      {
        number: 14,
        name: 'Kakuna',
        available: true,
        types: ['Bug', 'Poison'],
        ability: 'Shed Skin',
        hiddenAbility: '',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 120,
        stats: {
          hp: 45,
          atk: 25,
          def: 50,
          spa: 25,
          spd: 25,
          spe: 35
        },
        evolution: ['Weedle', 'Kakuna', 'Beedrill'],
        learnset: [
          { level: 1, move: 'Poison Sting' },
          { level: 7, move: 'Harden'       }
        ]
      },
      {
        number: 15,
        name: 'Beedrill',
        available: true,
        types: ['Bug', 'Poison'],
        ability: 'Swarm',
        hiddenAbility: 'Sniper',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 45,
        stats: {
          hp: 65,
          atk: 90,
          def: 40,
          spa: 45,
          spd: 80,
          spe: 75
        },
        evolution: ['Weedle', 'Kakuna', 'Beedrill'],
        learnset: [
          { level: 1,  move: 'U-turn'      },
          { level: 1,  move: 'Knock Off'   },
          { level: 1,  move: 'Twineedle'   },
          { level: 1,  move: 'Fury Attack' },
          { level: 10, move: 'Twineedle'   },
          { level: 12, move: 'Rage'        },
          { level: 16, move: 'Aerial Ace'  },
          { level: 18, move: 'Toxic'       },
          { level: 21, move: 'Assurance'   },
          { level: 24, move: 'Brick Break' },
          { level: 26, move: 'Endeavor'    },
          { level: 29, move: 'X-Scissor'   },
          { level: 31, move: 'Poison Jab'  },
          { level: 34, move: 'Drill Run'   },
          { level: 40, move: 'Megahorn'    }
        ]
      },
      {
        number: 15,
        name: 'Mega Beedrill',
        available: true,
        types: ['Bug', 'Poison'],
        ability: 'Adaptability',
        hiddenAbility: '',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 45,
        stats: {
          hp: 65,
          atk: 150,
          def: 40,
          spa: 15,
          spd: 80,
          spe: 145
        },
        evolution: '',
        learnset: [
          { level: 1,  move: 'U-turn'      },
          { level: 1,  move: 'Knock Off'   },
          { level: 1,  move: 'Twineedle'   },
          { level: 1,  move: 'Fury Attack' },
          { level: 10, move: 'Twineedle'   },
          { level: 12, move: 'Rage'        },
          { level: 16, move: 'Aerial Ace'  },
          { level: 18, move: 'Toxic'       },
          { level: 21, move: 'Assurance'   },
          { level: 24, move: 'Brick Break' },
          { level: 26, move: 'Endeavor'    },
          { level: 29, move: 'X-Scissor'   },
          { level: 31, move: 'Poison Jab'  },
          { level: 34, move: 'Drill Run'   },
          { level: 40, move: 'Megahorn'    }
        ]
      }
  ];