window.pokemonData = [
    {
      number: 1,
      name: 'Bulbasaur',
      available: true,
      types: ['Grass', 'Poison'],
      ability: 'Overgrow',
      hiddenAbility: 'Chlorophyll',
      aiAbility: '',
      gender: '87.5% male, 12.5% female',
      catchRate: 45,
      stats: {
        hp: 45,
        atk: 49,
        def: 49,
        spa: 65,
        spd: 65,
        spe: 45
      },
      evolution: ['Bulbasaur', 'Ivysaur', 'Venusaur'],
      evolutionMethod: ['Level 16', 'Level 32'],
      learnset: [
        { level: 1,  move: 'Tackle'      },
        { level: 1,  move: 'Growl'       },
        { level: 3,  move: 'Vine Whip'   },
        { level: 5,  move: 'Acid'        },
        { level: 8,  move: 'Headbutt'    },
        { level: 11, move: 'Growth'      },
        { level: 14, move: 'Poison Powder' },
        { level: 14, move: 'Sleep Powder'  },
        { level: 15, move: 'Razor Leaf'    },
        { level: 17, move: 'Take Down'     },
        { level: 20, move: 'Magical Leaf'  },
        { level: 22, move: 'Sludge Bomb'   },
        { level: 26, move: 'Seed Bomb'     },
        { level: 30, move: 'Toxic'         },
        { level: 30, move: 'Double-Edge'   },
        { level: 36, move: 'Leaf Blade'    },
        { level: 48, move: 'Giga Drain'    }
      ]
    },
    // more entries start here
    {
        number: 2,
        name: 'Ivysaur',
        available: true,
        types: ['Grass', 'Poison'],
        ability: 'Overgrow',
        hiddenAbility: 'Chlorophyll',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 60,
          atk: 62,
          def: 63,
          spa: 80,
          spd: 80,
          spe: 60
        },
        evolution: ['Bulbasaur', 'Ivysaur', 'Venusaur'],
        evolutionMethod: ['Level 16', 'Level 32'],
        learnset: [
          { level: 1,  move: 'Tackle'      },
          { level: 1,  move: 'Growl'       },
          { level: 3,  move: 'Vine Whip'   },
          { level: 5,  move: 'Acid'        },
          { level: 8,  move: 'Headbutt'    },
          { level: 12, move: 'Poison Powder' },
          { level: 15, move: 'Sleep Powder'  },
          { level: 16, move: 'Mega Drain'    },
          { level: 19, move: 'Take Down'     },
          { level: 22, move: 'Magical Leaf'  },
          { level: 25, move: 'Sludge Bomb'   },
          { level: 28, move: 'Seed Bomb'     },
          { level: 31, move: 'Toxic'         },
          { level: 33, move: 'Double-Edge'   },
          { level: 55, move: 'Giga Drain'    }
        ]
      },
      {
        number: 3,
        name: 'Venusaur',
        available: true,
        types: ['Grass', 'Poison'],
        ability: 'Overgrow',
        hiddenAbility: 'Chlorophyll',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 80,
          atk: 82,
          def: 83,
          spa: 100,
          spd: 100,
          spe: 80
        },
        evolution: ['Bulbasaur', 'Ivysaur', 'Venusaur'],
        evolutionMethod: ['Level 16', 'Level 32'],
        learnset: [
          { level: 1,  move: 'Giga Drain'     },
          { level: 1,  move: 'Ancient Power'  },
          { level: 1,  move: 'Tackle'         },
          { level: 1,  move: 'Growl'          },
          { level: 3,  move: 'Vine Whip'      },
          { level: 5,  move: 'Acid'           },
          { level: 8,  move: 'Headbutt'       },
          { level: 12, move: 'Poison Powder'  },
          { level: 15, move: 'Sleep Powder'   },
          { level: 18, move: 'Mega Drain'     },
          { level: 21, move: 'Take Down'      },
          { level: 25, move: 'Magical Leaf'   },
          { level: 28, move: 'Sludge Bomb'    },
          { level: 32, move: 'Seed Bomb'      },
          { level: 35, move: 'Toxic'          },
          { level: 36, move: 'Leaf Blade'     },
          { level: 40, move: 'Double-Edge'    },
          { level: 45, move: 'Earth Power'    }
        ]
      },
      {
        number: 3,
        name: 'Mega Venusaur',
        available: true,
        types: ['Grass', 'Poison'],
        ability: 'Thick Fat',
        hiddenAbility: '',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 80,
          atk: 100,
          def: 123,
          spa: 122,
          spd: 120,
          spe: 80
        },
        evolution: '',
        learnset: [
          { level: 1,  move: 'Giga Drain'     },
          { level: 1,  move: 'Ancient Power'  },
          { level: 1,  move: 'Tackle'         },
          { level: 1,  move: 'Growl'          },
          { level: 3,  move: 'Vine Whip'      },
          { level: 5,  move: 'Acid'           },
          { level: 8,  move: 'Headbutt'       },
          { level: 12, move: 'Poison Powder'  },
          { level: 15, move: 'Sleep Powder'   },
          { level: 18, move: 'Mega Drain'     },
          { level: 21, move: 'Take Down'      },
          { level: 25, move: 'Magical Leaf'   },
          { level: 28, move: 'Sludge Bomb'    },
          { level: 32, move: 'Seed Bomb'      },
          { level: 35, move: 'Toxic'          },
          { level: 36, move: 'Leaf Blade'     },
          { level: 40, move: 'Double-Edge'    },
          { level: 45, move: 'Earth Power'    }
        ]
      },
      {
        number: 4,
        name: 'Charmander',
        available: true,
        types: 'Fire',
        ability: 'Blaze',
        hiddenAbility: 'Solar Power',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 39,
          atk: 52,
          def: 43,
          spa: 60,
          spd: 50,
          spe: 65
        },
        evolution: ['Charmander', 'Charmeleon', 'Charizard'],
        evolutionMethod: ['Level 16', 'Level 36'],
        learnset: [
          { level: 1,  move: 'Scratch'        },
          { level: 1,  move: 'Growl'          },
          { level: 5,  move: 'Ember'          },
          { level: 8,  move: 'Smokescreen'    },
          { level: 11, move: 'Bite'          },
          { level: 14, move: 'Dragon Breath' },
          { level: 16, move: 'Fire Fang'     },
          { level: 20, move: 'Slash'          },
          { level: 25, move: 'Flame Burst'    },
          { level: 29, move: 'Dig'            },
          { level: 32, move: 'Flamethrower'   },
          { level: 36, move: 'Brick Break'    },
          { level: 40, move: 'Heat Wave'      },
          { level: 48, move: 'Flare Blitz'    }
        ]
      },
      {
        number: 5,
        name: 'Charmeleon',
        available: true,
        types: 'Fire',
        ability: 'Blaze',
        hiddenAbility: 'Solar Power',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 58,
          atk: 64,
          def: 58,
          spa: 80,
          spd: 65,
          spe: 80
        },
        evolution: ['Charmander', 'Charmeleon', 'Charizard'],
        evolutionMethod: ['Level 16', 'Level 36'],
        learnset: [
          { level: 1,  move: 'Scratch'        },
          { level: 1,  move: 'Growl'          },
          { level: 5,  move: 'Ember'          },
          { level: 8,  move: 'Smokescreen'    },
          { level: 11, move: 'Bite'           },
          { level: 14, move: 'Dragon Breath'  },
          { level: 16, move: 'Fire Fang'      },
          { level: 16, move: 'Metal Claw'     },
          { level: 20, move: 'Slash'          },
          { level: 25, move: 'Flame Burst'    },
          { level: 28, move: 'Dig'            },
          { level: 33, move: 'Dragon Claw'    },
          { level: 36, move: 'Flamethrower'   },
          { level: 36, move: 'Brick Break'    },
          { level: 40, move: 'Heat Wave'      },
          { level: 48, move: 'Flare Blitz'    }
        ]
      },
      {
        number: 6,
        name: 'Charizard',
        available: true,
        types: ['Fire', 'Flying'],
        ability: 'Blaze',
        hiddenAbility: 'Solar Power',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 78,
          atk: 84,
          def: 78,
          spa: 109,
          spd: 85,
          spe: 100
        },
        evolution: ['Charmander', 'Charmeleon', 'Charizard'],
        evolutionMethod: ['Level 16', 'Level 36'],
        learnset: [
          { level: 1,  move: 'Shadow Claw'    },
          { level: 1,  move: 'Hurricane'      },
          { level: 1,  move: 'Dragon Rush'    },
          { level: 1,  move: 'Scratch'        },
          { level: 1,  move: 'Growl'          },
          { level: 5,  move: 'Ember'          },
          { level: 8,  move: 'Smokescreen'    },
          { level: 11, move: 'Bite'           },
          { level: 14, move: 'Dragon Breath'  },
          { level: 16, move: 'Fire Fang'      },
          { level: 16, move: 'Metal Claw'     },
          { level: 20, move: 'Slash'          },
          { level: 25, move: 'Flame Burst'    },
          { level: 28, move: 'Dig'            },
          { level: 33, move: 'Dual Chop'      },
          { level: 36, move: 'Air Slash'      },
          { level: 41, move: 'Crunch'         },
          { level: 47, move: 'Dragon Claw'    },
          { level: 52, move: 'Heat Wave'      },
          { level: 57, move: 'Dual Wingbeat'  },
          { level: 62, move: 'Flare Blitz'    }
        ]
      },
      {
        number: 6,
        name: 'Mega Charizard X',
        available: true,
        types: ['Fire', 'Dragon'],
        ability: 'Tough Claws',
        hiddenAbility: '',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 78,
          atk: 130,
          def: 111,
          spa: 130,
          spd: 85,
          spe: 100
        },
        evolution: '',
        learnset: [
          { level: 1,  move: 'Shadow Claw'    },
          { level: 1,  move: 'Hurricane'      },
          { level: 1,  move: 'Dragon Rush'    },
          { level: 1,  move: 'Scratch'        },
          { level: 1,  move: 'Growl'          },
          { level: 5,  move: 'Ember'          },
          { level: 8,  move: 'Smokescreen'    },
          { level: 11, move: 'Bite'           },
          { level: 14, move: 'Dragon Breath'  },
          { level: 16, move: 'Fire Fang'      },
          { level: 16, move: 'Metal Claw'     },
          { level: 20, move: 'Slash'          },
          { level: 25, move: 'Flame Burst'    },
          { level: 28, move: 'Dig'            },
          { level: 33, move: 'Dual Chop'      },
          { level: 36, move: 'Air Slash'      },
          { level: 41, move: 'Crunch'         },
          { level: 47, move: 'Dragon Claw'    },
          { level: 52, move: 'Heat Wave'      },
          { level: 57, move: 'Dual Wingbeat'  },
          { level: 62, move: 'Flare Blitz'    }
        ]
      },
      {
        number: 6,
        name: 'Mega Charizard Y',
        available: true,
        types: ['Fire', 'Flying'],
        ability: 'Solar Power',
        hiddenAbility: '',
        aiAbility: 'Drought',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 78,
          atk: 104,
          def: 78,
          spa: 159,
          spd: 115,
          spe: 100
        },
        evolution: '',
        learnset: [
          { level: 1,  move: 'Shadow Claw'    },
          { level: 1,  move: 'Hurricane'      },
          { level: 1,  move: 'Dragon Rush'    },
          { level: 1,  move: 'Scratch'        },
          { level: 1,  move: 'Growl'          },
          { level: 5,  move: 'Ember'          },
          { level: 8,  move: 'Smokescreen'    },
          { level: 11, move: 'Bite'           },
          { level: 14, move: 'Dragon Breath'  },
          { level: 16, move: 'Fire Fang'      },
          { level: 16, move: 'Metal Claw'     },
          { level: 20, move: 'Slash'          },
          { level: 25, move: 'Flame Burst'    },
          { level: 28, move: 'Dig'            },
          { level: 33, move: 'Dual Chop'      },
          { level: 36, move: 'Air Slash'      },
          { level: 41, move: 'Crunch'         },
          { level: 47, move: 'Dragon Claw'    },
          { level: 52, move: 'Heat Wave'      },
          { level: 57, move: 'Dual Wingbeat'  },
          { level: 62, move: 'Flare Blitz'    }
        ]
      },
      {
        number: 7,
        name: 'Squirtle',
        available: true,
        types: ['Water'],
        ability: 'Torrent',
        hiddenAbility: 'Rain Dish',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 44,
          atk: 48,
          def: 65,
          spa: 50,
          spd: 64,
          spe: 43
        },
        evolution: ['Squirtle', 'Wartortle', 'Blastoise'],
        evolutionMethod: ['Level 16', 'Level 36'],
        learnset: [
          { level: 1,  move: 'Tackle'        },
          { level: 4,  move: 'Water Gun'     },
          { level: 4,  move: 'Tail Whip'     },
          { level: 9,  move: 'Bite'          },
          { level: 13, move: 'Bubblebeam'    },
          { level: 16, move: 'Aurora Beam'   },
          { level: 20, move: 'Aqua Jet'      },
          { level: 24, move: 'Aqua Tail'     },
          { level: 26, move: 'Yawn'          },
          { level: 29, move: 'Body Slam'     },
          { level: 32, move: 'Ice Punch'     },
          { level: 38, move: 'Wave Crash'    },
          { level: 43, move: 'Mirror Coat'   },
          { level: 49, move: 'Water Spout'   }
        ]
      },
      {
        number: 8,
        name: 'Wartortle',
        available: true,
        types: ['Water'],
        ability: 'Torrent',
        hiddenAbility: 'Rain Dish',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 59,
          atk: 63,
          def: 80,
          spa: 65,
          spd: 80,
          spe: 58
        },
        evolution: ['Squirtle', 'Wartortle', 'Blastoise'],
        evolutionMethod: ['Level 16', 'Level 36'],
        learnset: [
          { level: 1,  move: 'Tackle'        },
          { level: 4,  move: 'Water Gun'     },
          { level: 4,  move: 'Tail Whip'     },
          { level: 9,  move: 'Bite'          },
          { level: 13, move: 'Bubblebeam'    },
          { level: 16, move: 'Aurora Beam'   },
          { level: 22, move: 'Aqua Jet'      },
          { level: 26, move: 'Aqua Tail'     },
          { level: 29, move: 'Yawn'          },
          { level: 32, move: 'Body Slam'     },
          { level: 36, move: 'Brick Break'   },
          { level: 39, move: 'Ice Punch'     },
          { level: 44, move: 'Wave Crash'    },
          { level: 50, move: 'Mirror Coat'   },
          { level: 57, move: 'Water Spout'   }
        ]
      },
      {
        number: 9,
        name: 'Blastoise',
        available: true,
        types: ['Water'],
        ability: 'Torrent',
        hiddenAbility: 'Rain Dish',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 79,
          atk: 83,
          def: 100,
          spa: 85,
          spd: 105,
          spe: 78
        },
        evolution: ['Squirtle', 'Wartortle', 'Blastoise'],
        evolutionMethod: ['Level 16', 'Level 36'],
        learnset: [
          { level: 1,  move: 'Water Spout'   },
          { level: 1,  move: 'Water Pulse'   },
          { level: 1,  move: 'Aura Sphere'   },
          { level: 1,  move: 'Mirror Coat'   },
          { level: 1,  move: 'Fake Out'      },
          { level: 1,  move: 'Muddy Water'   },
          { level: 1,  move: 'Tackle'        },
          { level: 4,  move: 'Water Gun'     },
          { level: 4,  move: 'Tail Whip'     },
          { level: 9,  move: 'Bite'          },
          { level: 13, move: 'Bubblebeam'    },
          { level: 16, move: 'Aurora Beam'   },
          { level: 22, move: 'Aqua Jet'      },
          { level: 29, move: 'Aqua Tail'     },
          { level: 33, move: 'Yawn'          },
          { level: 37, move: 'Body Slam'     },
          { level: 40, move: 'Brick Break'   },
          { level: 42, move: 'Ice Punch'     },
          { level: 45, move: 'Double-Edge'   },
          { level: 50, move: 'Wave Crash'    }
        ]
      },
      {
        number: 9,
        name: 'Mega Blastoise',
        available: true,
        types: ['Water'],
        ability: 'Mega Launcher',
        hiddenAbility: '',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        stats: {
          hp: 79,
          atk: 103,
          def: 120,
          spa: 135,
          spd: 115,
          spe: 78
        },
        evolution: '',
        learnset: [
          { level: 1,  move: 'Water Spout'   },
          { level: 1,  move: 'Water Pulse'   },
          { level: 1,  move: 'Aura Sphere'   },
          { level: 1,  move: 'Mirror Coat'   },
          { level: 1,  move: 'Fake Out'      },
          { level: 1,  move: 'Muddy Water'   },
          { level: 1,  move: 'Tackle'        },
          { level: 4,  move: 'Water Gun'     },
          { level: 4,  move: 'Tail Whip'     },
          { level: 9,  move: 'Bite'          },
          { level: 13, move: 'Bubblebeam'    },
          { level: 16, move: 'Aurora Beam'   },
          { level: 22, move: 'Aqua Jet'      },
          { level: 29, move: 'Aqua Tail'     },
          { level: 33, move: 'Yawn'          },
          { level: 37, move: 'Body Slam'     },
          { level: 40, move: 'Brick Break'   },
          { level: 42, move: 'Ice Punch'     },
          { level: 45, move: 'Double-Edge'   },
          { level: 50, move: 'Wave Crash'    }
        ]
      },
      {
        number: 10,
        name: 'Caterpie',
        available: false,
        types: ['Bug'],
        ability: 'Shield Dust',
        hiddenAbility: 'Run Away',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 255,
        stats: {
          hp: 45,
          atk: 30,
          def: 35,
          spa: 20,
          spd: 20,
          spe: 45
        },
        evolution: ['Caterpie', 'Metapod', 'Butterfree'],
        evolutionMethod: ['Level 7', 'Level 10'],
        learnset: [
          { level: 1, move: 'Tackle'     },
          { level: 1, move: 'String Shot' },
          { level: 9, move: 'Bug Bite'   }
        ]
      },
      {
        number: 11,
        name: 'Metapod',
        available: false,
        types: ['Bug'],
        ability: 'Shed Skin',
        hiddenAbility: '',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 120,
        stats: {
          hp: 50,
          atk: 20,
          def: 55,
          spa: 25,
          spd: 25,
          spe: 30
        },
        evolution: ['Caterpie', 'Metapod', 'Butterfree'],
        evolutionMethod: ['Level 7', 'Level 10'],
        learnset: [
          { level: 1, move: 'Tackle' },
          { level: 7, move: 'Harden' }
        ]
      },
      {
        number: 12,
        name: 'Butterfree',
        available: false,
        types: ['Bug', 'Flying'],
        ability: 'Compound Eyes',
        hiddenAbility: 'Tinted Lens',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 45,
        heldItem: {name: "Silver Powder", rate: 5},
        stats: {
          hp: 60,
          atk: 45,
          def: 50,
          spa: 90,
          spd: 80,
          spe: 70
        },
        evolution: ['Caterpie', 'Metapod', 'Butterfree'],
        evolutionMethod: ['Level 7', 'Level 10'],
        learnset: [
          { level: 1,  move: 'Rage Powder' },
          { level: 1,  move: 'Pollen Puff' },
          { level: 1,  move: 'Harden'      },
          { level: 1,  move: 'Tackle'      },
          { level: 1,  move: 'String Shot' },
          { level: 1,  move: 'Bug Bite'    },
          { level: 1,  move: 'Confusion'   },
          { level: 10, move: 'Confusion'   },
          { level: 10, move: 'Mega Drain'  },
          { level: 12, move: 'Supersonic'  },
          { level: 13, move: 'Poison Powder' },
          { level: 13, move: 'Stun Spore'    },
          { level: 15, move: 'Sleep Powder'  },
          { level: 16, move: 'Psybeam'     },
          { level: 19, move: 'Silver Wind' },
          { level: 22, move: 'Safeguard'   },
          { level: 24, move: 'U-turn'      },
          { level: 28, move: 'Air Slash'   },
          { level: 31, move: 'Giga Drain'  },
          { level: 34, move: 'Bug Buzz'    },
          { level: 38, move: 'Hurricane'   },
          { level: 42, move: 'Tailwind'    }
        ]
      },
      {
        number: 13,
        name: 'Weedle',
        available: true,
        types: ['Bug', 'Poison'],
        ability: 'Shield Dust',
        hiddenAbility: 'Run Away',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 255,
        stats: {
          hp: 40,
          atk: 35,
          def: 30,
          spa: 20,
          spd: 20,
          spe: 50
        },
        evolution: ['Weedle', 'Kakuna', 'Beedrill'],
        evolutionMethod: ['Level 7', 'Level 10'],
        learnset: [
          { level: 1, move: 'Poison Sting' },
          { level: 1, move: 'String Shot'  },
          { level: 9, move: 'Bug Bite'     }
        ]
      },
      {
        number: 14,
        name: 'Kakuna',
        available: true,
        types: ['Bug', 'Poison'],
        ability: 'Shed Skin',
        hiddenAbility: '',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 120,
        stats: {
          hp: 45,
          atk: 25,
          def: 50,
          spa: 25,
          spd: 25,
          spe: 35
        },
        evolution: ['Weedle', 'Kakuna', 'Beedrill'],
        evolutionMethod: ['Level 7', 'Level 10'],
        learnset: [
          { level: 1, move: 'Poison Sting' },
          { level: 7, move: 'Harden'       }
        ]
      },
      {
        number: 15,
        name: 'Beedrill',
        available: true,
        types: ['Bug', 'Poison'],
        ability: 'Swarm',
        hiddenAbility: 'Sniper',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 45,
        stats: {
          hp: 65,
          atk: 90,
          def: 40,
          spa: 45,
          spd: 80,
          spe: 75
        },
        evolution: ['Weedle', 'Kakuna', 'Beedrill'],
        evolutionMethod: ['Level 7', 'Level 10'],
        learnset: [
          { level: 1,  move: 'U-turn'      },
          { level: 1,  move: 'Knock Off'   },
          { level: 1,  move: 'Twineedle'   },
          { level: 1,  move: 'Fury Attack' },
          { level: 10, move: 'Twineedle'   },
          { level: 12, move: 'Rage'        },
          { level: 16, move: 'Aerial Ace'  },
          { level: 18, move: 'Toxic'       },
          { level: 21, move: 'Assurance'   },
          { level: 24, move: 'Brick Break' },
          { level: 26, move: 'Endeavor'    },
          { level: 29, move: 'X-Scissor'   },
          { level: 31, move: 'Poison Jab'  },
          { level: 34, move: 'Drill Run'   },
          { level: 40, move: 'Megahorn'    }
        ]
      },
      {
        number: 15,
        name: 'Mega Beedrill',
        available: true,
        types: ['Bug', 'Poison'],
        ability: 'Adaptability',
        hiddenAbility: '',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 45,
        stats: {
          hp: 65,
          atk: 150,
          def: 40,
          spa: 15,
          spd: 80,
          spe: 145
        },
        evolution: '',
        learnset: [
          { level: 1,  move: 'U-turn'      },
          { level: 1,  move: 'Knock Off'   },
          { level: 1,  move: 'Twineedle'   },
          { level: 1,  move: 'Fury Attack' },
          { level: 10, move: 'Twineedle'   },
          { level: 12, move: 'Rage'        },
          { level: 16, move: 'Aerial Ace'  },
          { level: 18, move: 'Toxic'       },
          { level: 21, move: 'Assurance'   },
          { level: 24, move: 'Brick Break' },
          { level: 26, move: 'Endeavor'    },
          { level: 29, move: 'X-Scissor'   },
          { level: 31, move: 'Poison Jab'  },
          { level: 34, move: 'Drill Run'   },
          { level: 40, move: 'Megahorn'    }
        ]
      },
      {
        number: 16,
        name: 'Pidgey',
        available: true,
        types: ['Normal', 'Flying'],
        abilities: ['Keen Eye', 'Tangled Feet'],
        hiddenAbility: 'Big Pecks',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 255,
        stats: {
          hp: 40,
          atk: 45,
          def: 40,
          spa: 35,
          spd: 35,
          spe: 56
        },
        evolution: ['Pidgey', 'Pidgeotto', 'Pidgeot'],
        evolutionMethod: ['Level 16', 'Level 32'],
        learnset: [
          { level: 1,  move: 'Tackle'        },
          { level: 2,  move: 'Feather Dance' },
          { level: 5,  move: 'Sand Attack'   },
          { level: 9,  move: 'Gust'          },
          { level: 12, move: 'Quick Attack'  },
          { level: 15, move: 'Wing Attack'   },
          { level: 18, move: 'Secret Power'  },
          { level: 23, move: 'Aerial Ace'    },
          { level: 25, move: 'Extreme Speed' },
          { level: 27, move: 'Air Slash'     },
          { level: 30, move: 'Double-Edge'   },
          { level: 35, move: 'Brave Bird'    }
        ]
      },
      {
        number: 17,
        name: 'Pidgeotto',
        available: true,
        types: ['Normal', 'Flying'],
        abilities: ['Keen Eye', 'Tangled Feet'],
        hiddenAbility: 'Big Pecks',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 120,
        stats: {
          hp: 63,
          atk: 60,
          def: 55,
          spa: 50,
          spd: 50,
          spe: 71
        },
        evolution: ['Pidgey', 'Pidgeotto', 'Pidgeot'],
        evolutionMethod: ['Level 16', 'Level 32'],
        learnset: [
          { level: 1,  move: 'Tackle'        },
          { level: 2,  move: 'Feather Dance' },
          { level: 5,  move: 'Sand Attack'   },
          { level: 9,  move: 'Gust'          },
          { level: 12, move: 'Quick Attack'  },
          { level: 15, move: 'Wing Attack'   },
          { level: 22, move: 'Secret Power'  },
          { level: 28, move: 'Aerial Ace'    },
          { level: 33, move: 'Air Slash'     },
          { level: 36, move: 'Steel Wing'    },
          { level: 39, move: 'Double-Edge'   },
          { level: 45, move: 'Brave Bird'    }
        ]
      },
      {
        number: 18,
        name: 'Pidgeot',
        available: true,
        types: ['Normal', 'Flying'],
        abilities: ['Keen Eye', 'Tangled Feet'],
        hiddenAbility: 'Big Pecks',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 45,
        stats: {
          hp: 83,
          atk: 80,
          def: 75,
          spa: 70,
          spd: 70,
          spe: 101
        },
        evolution: ['Pidgey', 'Pidgeotto', 'Pidgeot'],
        evolutionMethod: ['Level 16', 'Level 32'],
        learnset: [
          { level: 1,  move: 'Roost'         },
          { level: 1,  move: 'Tackle'        },
          { level: 2,  move: 'Feather Dance' },
          { level: 5,  move: 'Sand Attack'   },
          { level: 9,  move: 'Gust'          },
          { level: 12, move: 'Quick Attack'  },
          { level: 15, move: 'Wing Attack'   },
          { level: 22, move: 'Secret Power'  },
          { level: 30, move: 'Aerial Ace'    },
          { level: 36, move: 'Air Slash'     },
          { level: 40, move: 'Heat Wave'     },
          { level: 43, move: 'Steel Wing'    },
          { level: 46, move: 'Double-Edge'   },
          { level: 51, move: 'Brave Bird'    },
          { level: 55, move: 'Hurricane'     }
        ]
      },
      {
        number: 18,
        name: 'Mega Pidgeot',
        available: true,
        types: ['Normal', 'Flying'],
        ability: 'No Guard',
        hiddenAbility: '',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 45,
        stats: {
          hp: 83,
          atk: 80,
          def: 80,
          spa: 135,
          spd: 80,
          spe: 121
        },
        evolution: '',
        learnset: [
          { level: 1,  move: 'Roost'         },
          { level: 1,  move: 'Tackle'        },
          { level: 2,  move: 'Feather Dance' },
          { level: 5,  move: 'Sand Attack'   },
          { level: 9,  move: 'Gust'          },
          { level: 12, move: 'Quick Attack'  },
          { level: 15, move: 'Wing Attack'   },
          { level: 22, move: 'Secret Power'  },
          { level: 30, move: 'Aerial Ace'    },
          { level: 36, move: 'Air Slash'     },
          { level: 40, move: 'Heat Wave'     },
          { level: 43, move: 'Steel Wing'    },
          { level: 46, move: 'Double-Edge'   },
          { level: 51, move: 'Brave Bird'    }
        ]
      },
      {
        number: 19,
        name: 'Rattata',
        available: false,
        types: 'Normal',
        ability: 'Guts',
        hiddenAbility: 'Hustle',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 255,
        heldItem: {name: "Chilan Berry", rate: 5},
        stats: {
          hp: 30,
          atk: 56,
          def: 35,
          spa: 25,
          spd: 35,
          spe: 72
        },
        evolution: ['Rattata', 'Raticate'],
        evolutionMethod: ['Level 20'],
        learnset: [
          { level: 1,  move: 'Tackle'       },
          { level: 1,  move: 'Tail Whip'    },
          { level: 4,  move: 'Quick Attack' },
          { level: 10, move: 'Bite'         },
          { level: 13, move: 'Pursuit'      },
          { level: 16, move: 'Hyper Fang'   },
          { level: 19, move: 'Assurance'    },
          { level: 22, move: 'Crunch'       },
          { level: 25, move: 'Sucker Punch' },
          { level: 28, move: 'Super Fang'   },
          { level: 31, move: 'Double-Edge'  },
          { level: 34, move: 'Endeavor'     },
          { level: 36, move: 'Facade'       }
        ]
      },
      {
        number: 20,
        name: 'Raticate',
        available: false,
        types: 'Normal',
        ability: 'Guts',
        hiddenAbility: 'Hustle',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 127,
        heldItem: {name: "Sitrus Berry", rate: 5},
        stats: {
          hp: 55,
          atk: 81,
          def: 60,
          spa: 50,
          spd: 70,
          spe: 97
        },
        evolution: ['Rattata', 'Raticate'],
        evolutionMethod: ['Level 20'],
        learnset: [
          { level: 1,  move: 'Tackle'       },
          { level: 1,  move: 'Tail Whip'    },
          { level: 4,  move: 'Quick Attack' },
          { level: 10, move: 'Bite'         },
          { level: 13, move: 'Pursuit'      },
          { level: 16, move: 'Hyper Fang'   },
          { level: 19, move: 'Assurance'    },
          { level: 22, move: 'Crunch'       },
          { level: 25, move: 'Sucker Punch' },
          { level: 32, move: 'Super Fang'   },
          { level: 35, move: 'Double-Edge'  },
          { level: 37, move: 'Endeavor'     },
          { level: 41, move: 'Facade'       },
          { level: 44, move: 'Reversal'     }
        ]
      },
      {
        number: 19,
        name: 'Alolan Rattata',
        available: false,
        types: ['Dark', 'Normal'],
        ability: 'Guts',
        hiddenAbility: 'Thick Fat',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 255,
        stats: {
          hp: 30,
          atk: 56,
          def: 35,
          spa: 25,
          spd: 35,
          spe: 72
        },
        evolution: ['Alolan Rattata', 'Alolan Raticate'],
        evolutionMethod: ['Level 20 at Night'],
        learnset: [
          { level: 1,  move: 'Tackle'       },
          { level: 1,  move: 'Tail Whip'    },
          { level: 4,  move: 'Quick Attack' },
          { level: 10, move: 'Bite'         },
          { level: 13, move: 'Pursuit'      },
          { level: 16, move: 'Hyper Fang'   },
          { level: 19, move: 'Assurance'    },
          { level: 22, move: 'Crunch'       },
          { level: 25, move: 'Sucker Punch' },
          { level: 28, move: 'Super Fang'   },
          { level: 31, move: 'Double-Edge'  },
          { level: 34, move: 'Endeavor'     },
          { level: 36, move: 'Facade'       }
        ]
      },
      {
        number: 20,
        name: 'Alolan Raticate',
        available: false,
        types: ['Dark', 'Normal'],
        ability: 'Guts',
        hiddenAbility: 'Thick Fat',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 127,
        stats: {
          hp: 75,
          atk: 71,
          def: 70,
          spa: 40,
          spd: 80,
          spe: 77
        },
        evolution: ['Alolan Rattata', 'Alolan Raticate'],
        evolutionMethod: ['Level 20 at Night'],
        learnset: [
          { level: 1,  move: 'Tackle'       },
          { level: 1,  move: 'Tail Whip'    },
          { level: 4,  move: 'Quick Attack' },
          { level: 10, move: 'Bite'         },
          { level: 13, move: 'Pursuit'      },
          { level: 16, move: 'Hyper Fang'   },
          { level: 19, move: 'Assurance'    },
          { level: 22, move: 'Crunch'       },
          { level: 25, move: 'Sucker Punch' },
          { level: 32, move: 'Super Fang'   },
          { level: 35, move: 'Double-Edge'  },
          { level: 37, move: 'Endeavor'     },
          { level: 41, move: 'Facade'       },
          { level: 44, move: 'Reversal'     }
        ]
      },
      {
        number: 21,
        name: 'Spearow',
        available: false,
        types: ['Normal', 'Flying'],
        ability: 'Keen Eye',
        hiddenAbility: 'Sniper',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 255,
        stats: {
          hp: 40,
          atk: 60,
          def: 30,
          spa: 31,
          spd: 31,
          spe: 70
        },
        evolution: ['Spearow', 'Fearow'],
        evolutionMethod: ['Level 20'],
        learnset: [
          { level: 1,  move: 'Peck'         },
          { level: 1,  move: 'Growl'        },
          { level: 4,  move: 'Leer'         },
          { level: 6,  move: 'Pursuit'      },
          { level: 9,  move: 'Assurance'    },
          { level: 11, move: 'Secret Power' },
          { level: 15, move: 'Aerial Ace'   },
          { level: 18, move: 'Rage'         },
          { level: 21, move: 'Quick Attack' },
          { level: 25, move: 'Steel Wing'   },
          { level: 31, move: 'Drill Peck'   },
          { level: 36, move: 'Double-Edge'  }
        ]
      },
      {
        number: 22,
        name: 'Fearow',
        available: false,
        types: ['Normal', 'Flying'],
        ability: 'Keen Eye',
        hiddenAbility: 'Sniper',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 90,
        stats: {
          hp: 65,
          atk: 90,
          def: 65,
          spa: 61,
          spd: 61,
          spe: 100
        },
        evolution: ['Spearow', 'Fearow'],
        evolutionMethod: ['Level 20'],
        learnset: [
          { level: 1,  move: 'Roost'        },
          { level: 1,  move: 'Peck'         },
          { level: 1,  move: 'Growl'        },
          { level: 4,  move: 'Leer'         },
          { level: 6,  move: 'Pursuit'      },
          { level: 9,  move: 'Assurance'    },
          { level: 11, move: 'Secret Power' },
          { level: 15, move: 'Aerial Ace'   },
          { level: 22, move: 'Rage'         },
          { level: 26, move: 'Quick Attack' },
          { level: 29, move: 'Steel Wing'   },
          { level: 34, move: 'Drill Run'    },
          { level: 39, move: 'Drill Peck'   },
          { level: 43, move: 'Double-Edge'  }
        ]
      },
      {
        number: 23,
        name: 'Ekans',
        available: true,
        types: ['Poison'],
        ability: 'Intimidate',
        hiddenAbility: 'Unnerve',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 255,
        stats: {
          hp: 35,
          atk: 60,
          def: 44,
          spa: 40,
          spd: 54,
          spe: 55
        },
        evolution: ['Ekans', 'Arbok'],
        evolutionMethod: ['Level 22'],
        learnset: [
          { level: 1,  move: 'Wrap'         },
          { level: 1,  move: 'Leer'         },
          { level: 4,  move: 'Acid'         },
          { level: 8,  move: 'Bite'         },
          { level: 12, move: 'Glare'        },
          { level: 15, move: 'Mud Shot'     },
          { level: 19, move: 'Dig'          },
          { level: 22, move: 'Sludge Bomb'  },
          { level: 26, move: 'Body Slam'    },
          { level: 29, move: 'Crunch'       },
          { level: 33, move: 'Poison Tail'  },
          { level: 35, move: 'Psychic Fangs'},
          { level: 39, move: 'Rock Slide'   },
          { level: 44, move: 'Sucker Punch' },
          { level: 47, move: 'Gunk Shot'    }
        ]
      },
      {
        number: 24,
        name: 'Arbok',
        available: true,
        types: ['Poison'],
        ability: 'Intimidate',
        hiddenAbility: 'Unnerve',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 90,
        stats: {
          hp: 60,
          atk: 95,
          def: 69,
          spa: 65,
          spd: 79,
          spe: 80
        },
        evolution: ['Ekans', 'Arbok'],
        evolutionMethod: ['Level 22'],
        learnset: [
          { level: 1,  move: 'Earthquake'    },
          { level: 1,  move: 'Giga Drain'    },
          { level: 1,  move: 'Fire Fang'     },
          { level: 1,  move: 'Ice Fang'      },
          { level: 1,  move: 'Wrap'          },
          { level: 1,  move: 'Leer'          },
          { level: 4,  move: 'Acid'          },
          { level: 8,  move: 'Bite'          },
          { level: 12, move: 'Glare'         },
          { level: 15, move: 'Mud Shot'      },
          { level: 19, move: 'Dig'           },
          { level: 22, move: 'Sludge Bomb'   },
          { level: 25, move: 'Leech Life'    },
          { level: 29, move: 'Body Slam'     },
          { level: 31, move: 'Crunch'        },
          { level: 34, move: 'Thunder Fang'  },
          { level: 37, move: 'Poison Tail'   },
          { level: 41, move: 'Psychic Fangs' },
          { level: 46, move: 'Rock Slide'    },
          { level: 49, move: 'Sucker Punch'  },
          { level: 52, move: 'Gunk Shot'     }
        ]
      },
      {
        number: 25,
        name: 'Pikachu',
        available: true,
        types: ['Electric'],
        ability: 'Static',
        hiddenAbility: '',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 190,
        stats: {
          hp: 35,
          atk: 55,
          def: 40,
          spa: 50,
          spd: 50,
          spe: 90
        },
        preEvolution: ['Pichu'],
        evolutionSplit: ['Raichu','Alolan Raichu'],
        evolutionMethod: ['Thunder Stone', 'Dawn Stone'],
        learnset: [
          { level: 1,  move: 'Charm'        },
          { level: 1,  move: 'Thunder Shock'},
          { level: 1,  move: 'Tail Whip'    },
          { level: 1,  move: 'Nuzzle'       },
          { level: 1,  move: 'Quick Attack' },
          { level: 5,  move: 'Growl'        },
          { level: 7,  move: 'Thunder Wave' },
          { level: 10, move: 'Quick Attack' },
          { level: 12, move: 'Electro Ball' },
          { level: 16, move: 'Shock Wave'   },
          { level: 22, move: 'Spark'        },
          { level: 26, move: 'Play Rough'   },
          { level: 30, move: 'Iron Tail'    },
          { level: 33, move: 'Thunderbolt'  },
          { level: 37, move: 'Surf'         },
          { level: 42, move: 'Volt Switch'  },
          { level: 46, move: 'Volt Tackle'  }
        ]
      },
      {
        number: 26,
        name: 'Raichu',
        available: true,
        types: ['Electric'],
        ability: 'Static',
        hiddenAbility: '',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 75,
        stats: {
          hp: 60,
          atk: 90,
          def: 55,
          spa: 90,
          spd: 80,
          spe: 110
        },
        evolution: ['Pichu', 'Pikachu', 'Raichu'],
        evolutionMethod: ['Any Level', 'Thunder Stone'],
        learnset: [
          { level: 1,  move: 'Thunder Punch' },
          { level: 1,  move: 'Charm'         },
          { level: 1,  move: 'Thunder Shock' },
          { level: 1,  move: 'Tail Whip'     },
          { level: 1,  move: 'Nuzzle'        },
          { level: 1,  move: 'Quick Attack'  },
          { level: 5,  move: 'Growl'         },
          { level: 7,  move: 'Thunder Wave'  },
          { level: 14, move: 'Quick Attack'  },
          { level: 19, move: 'Electro Ball'  },
          { level: 25, move: 'Shock Wave'    },
          { level: 28, move: 'Spark'         },
          { level: 32, move: 'Play Rough'    },
          { level: 36, move: 'Iron Tail'     },
          { level: 40, move: 'Thunderbolt'   },
          { level: 45, move: 'Surf'          },
          { level: 49, move: 'Volt Switch'   },
          { level: 53, move: 'Volt Tackle'   }
        ]
      },
      {
        number: 26,
        name: 'Alolan Raichu',
        available: true,
        types: ['Electric', 'Psychic'],
        abilities: ['Surge Surfer', 'Static'],
        hiddenAbility: 'Levitate',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 75,
        stats: {
          hp: 60,
          atk: 85,
          def: 50,
          spa: 95,
          spd: 85,
          spe: 110
        },
        evolution: ['Pichu', 'Pikachu', 'Alolan Raichu'],
        evolutionMethod: ['Any Level', 'Dawn Stone'],
        learnset: [
          { level: 1,  move: 'Charm'         },
          { level: 1,  move: 'Thunder Shock' },
          { level: 1,  move: 'Tail Whip'     },
          { level: 1,  move: 'Nuzzle'        },
          { level: 1,  move: 'Quick Attack'  },
          { level: 5,  move: 'Growl'         },
          { level: 7,  move: 'Thunder Wave'  },
          { level: 14, move: 'Quick Attack'  },
          { level: 19, move: 'Electro Ball'  },
          { level: 25, move: 'Shock Wave'    },
          { level: 28, move: 'Psybeam'       },
          { level: 32, move: 'Play Rough'    },
          { level: 36, move: 'Psychic'       },
          { level: 40, move: 'Thunderbolt'   },
          { level: 45, move: 'Surf'          },
          { level: 49, move: 'Volt Switch'   },
          { level: 53, move: 'Volt Tackle'   }
        ]
      },
      {
        number: 27,
        name: 'Sandshrew',
        available: false,
        types: ['Ground'],
        ability: 'Sand Veil',
        hiddenAbility: 'Sand Rush',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 255,
        stats: {
          hp: 50,
          atk: 75,
          def: 85,
          spa: 20,
          spd: 30,
          spe: 40
        },
        evolution: ['Sandshrew', 'Sandslash'],
        evolutionMethod: ['Level 22'],
        learnset: [
          { level: 1,  move: 'Scratch'          },
          { level: 3,  move: 'Poison Sting'     },
          { level: 4,  move: 'Sand Attack'      },
          { level: 8,  move: 'Rollout'          },
          { level: 11, move: 'Bulldoze'         },
          { level: 14, move: 'Magnitude'        },
          { level: 18, move: 'Slash'            },
          { level: 22, move: 'Brick Break'      },
          { level: 28, move: 'Stomping Tantrum' },
          { level: 31, move: 'Rock Slide'       },
          { level: 34, move: 'Night Slash'      },
          { level: 38, move: 'X-Scissor'        },
          { level: 42, move: 'Earthquake'       }
        ]
      },
      {
        number: 28,
        name: 'Sandslash',
        available: false,
        types: ['Ground'],
        ability: 'Sand Veil',
        hiddenAbility: 'Sand Rush',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 90,
        stats: {
          hp: 75,
          atk: 100,
          def: 110,
          spa: 45,
          spd: 55,
          spe: 65
        },
        evolution: ['Sandshrew', 'Sandslash'],
        evolutionMethod: ['Level 22'],
        learnset: [
          { level: 1,  move: 'Scratch'          },
          { level: 3,  move: 'Poison Sting'     },
          { level: 4,  move: 'Sand Attack'      },
          { level: 8,  move: 'Rollout'          },
          { level: 15, move: 'Bulldoze'         },
          { level: 19, move: 'Magnitude'        },
          { level: 25, move: 'Slash'            },
          { level: 29, move: 'Brick Break'      },
          { level: 33, move: 'Stomping Tantrum' },
          { level: 36, move: 'Rock Slide'       },
          { level: 38, move: 'Night Slash'      },
          { level: 43, move: 'X-Scissor'        },
          { level: 45, move: 'Crush Claw'       },
          { level: 49, move: 'Earthquake'       }
        ]
      },
      {
        number: 27,
        name: 'Alolan Sandshrew',
        available: true,
        types: ['Ice', 'Steel'],
        ability: 'Slush Rush',
        hiddenAbility: '',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 255,
        stats: {
          hp: 50,
          atk: 75,
          def: 90,
          spa: 10,
          spd: 35,
          spe: 40
        },
        evolution: ['Alolan Sandshrew', 'Alolan Sandslash'],
        evolutionMethod: ['Ice Stone'],
        learnset: [
          { level: 1,  move: 'Scratch'       },
          { level: 3,  move: 'Bide'          },
          { level: 5,  move: 'Powder Snow'   },
          { level: 7,  move: 'Ice Ball'      },
          { level: 9,  move: 'Metal Claw'    },
          { level: 11, move: 'Aurora Beam'   },
          { level: 14, move: 'Bulldoze'      },
          { level: 17, move: 'Swift'         },
          { level: 22, move: 'Ice Punch'     },
          { level: 26, move: 'Slash'         },
          { level: 30, move: 'Ice Shard'     },
          { level: 33, move: 'Iron Head'     },
          { level: 37, move: 'Ice Spinner'   },
          { level: 41, move: 'Earthquake'    },
          { level: 45, move: 'Blizzard'      }
        ]
      },
      {
        number: 28,
        name: 'Alolan Sandslash',
        available: true,
        types: ['Ice', 'Steel'],
        ability: 'Slush Rush',
        hiddenAbility: '',
        aiAbility: '',
        gender: '50% male, 50% female',
        catchRate: 90,
        stats: {
          hp: 75,
          atk: 100,
          def: 120,
          spa: 25,
          spd: 65,
          spe: 65
        },
        evolution: ['Alolan Sandshrew', 'Alolan Sandslash'],
        evolutionMethod: ['Ice Stone'],
        learnset: [
          { level: 1,  move: 'Scratch'       },
          { level: 3,  move: 'Bide'          },
          { level: 5,  move: 'Powder Snow'   },
          { level: 7,  move: 'Ice Ball'      },
          { level: 10, move: 'Metal Claw'    },
          { level: 12, move: 'Aurora Beam'   },
          { level: 16, move: 'Bulldoze'      },
          { level: 20, move: 'Swift'         },
          { level: 25, move: 'Ice Punch'     },
          { level: 28, move: 'Slash'         },
          { level: 33, move: 'Ice Shard'     },
          { level: 35, move: 'Iron Head'     },
          { level: 40, move: 'Ice Spinner'   },
          { level: 44, move: 'Earthquake'    },
          { level: 49, move: 'Icicle Crash'  }
        ]
      },
      {
        number: 29,
        name: 'Nidoran♀',
        available: true,
        types: ['Poison'],
        abilities: ['Poison Point', 'Rivalry'],
        hiddenAbility: 'Hustle',
        aiAbility: '',
        gender: '100% female',
        catchRate: 235,
        stats: {
          hp: 55,
          atk: 47,
          def: 52,
          spa: 40,
          spd: 40,
          spe: 41
        },
        evolution: ['Nidoran♀', 'Nidorina', 'Nidoqueen'],
        learnset: [
          { level: 1,  move: 'Growl'        },
          { level: 1,  move: 'Poison Sting' },
          { level: 1,  move: 'Scratch'      },
          { level: 9,  move: 'Sludge'       },
          { level: 13, move: 'Bite'         },
          { level: 16, move: 'Double Kick'  },
          { level: 21, move: 'Toxic'        },
          { level: 24, move: 'Shadow Claw'  },
          { level: 27, move: 'Sludge Bomb'  },
          { level: 30, move: 'Crunch'       },
          { level: 34, move: 'Shadow Claw'  },
          { level: 38, move: 'Poison Fang'  }
        ]
      },
      {
        number: 30,
        name: 'Nidorina',
        available: true,
        types: ['Poison'],
        abilities: ['Poison Point', 'Rivalry'],
        hiddenAbility: 'Hustle',
        aiAbility: '',
        gender: '100% female',
        catchRate: 120,
        stats: {
          hp: 70,
          atk: 62,
          def: 67,
          spa: 55,
          spd: 55,
          spe: 56
        },
        evolution: ['Nidoran♀', 'Nidorina', 'Nidoqueen'],
        learnset: [
          { level: 1,  move: 'Growl'        },
          { level: 1,  move: 'Poison Sting' },
          { level: 1,  move: 'Scratch'      },
          { level: 9,  move: 'Sludge'       },
          { level: 13, move: 'Bite'         },
          { level: 16, move: 'Double Kick'  },
          { level: 21, move: 'Toxic'        },
          { level: 25, move: 'Shadow Claw'  },
          { level: 28, move: 'Sludge Bomb'  },
          { level: 31, move: 'Crunch'       },
          { level: 36, move: 'Shadow Claw'  },
          { level: 40, move: 'Poison Fang'  }
        ]
      },
      {
        number: 31,
        name: 'Nidoqueen',
        available: true,
        types: ['Poison', 'Ground'],
        abilities: ['Poison Point', 'Rivalry'],
        hiddenAbility: 'Sheer Force',
        aiAbility: '',
        gender: '100% female',
        catchRate: 45,
        stats: {
          hp: 90,
          atk: 92,
          def: 87,
          spa: 75,
          spd: 85,
          spe: 76
        },
        evolution: ['Nidoran♀', 'Nidorina', 'Nidoqueen'],
        learnset: [
          { level: 1,  move: 'Super Fang'    },
          { level: 1,  move: 'Counter'       },
          { level: 1,  move: 'Growl'         },
          { level: 1,  move: 'Poison Sting'  },
          { level: 1,  move: 'Scratch'       },
          { level: 9,  move: 'Sludge'        },
          { level: 13, move: 'Bite'          },
          { level: 16, move: 'Double Kick'   },
          { level: 21, move: 'Toxic'         },
          { level: 25, move: 'Shadow Claw'   },
          { level: 28, move: 'Sludge Bomb'   },
          { level: 35, move: 'Crunch'        },
          { level: 39, move: 'Shadow Claw'   },
          { level: 44, move: 'Poison Fang'   },
          { level: 47, move: 'Earthquake'    },
          { level: 49, move: 'Superpower'    }
        ]
      },
      {
        number: 32,
        name: 'Nidoran♂',
        available: true,
        types: ['Poison'],
        abilities: ['Poison Point', 'Rivalry'],
        hiddenAbility: 'Hustle',
        aiAbility: '',
        gender: '100% male',
        catchRate: 235,
        stats: {
          hp: 46,
          atk: 57,
          def: 40,
          spa: 40,
          spd: 40,
          spe: 50
        },
        evolution: ['Nidoran♂', 'Nidorino', 'Nidoking'],
        learnset: [
          { level: 1,  move: 'Growl'         },
          { level: 1,  move: 'Poison Sting'  },
          { level: 1,  move: 'Scratch'       },
          { level: 9,  move: 'Sludge'        },
          { level: 13, move: 'Bite'          },
          { level: 16, move: 'Double Kick'   },
          { level: 21, move: 'Toxic'         },
          { level: 24, move: 'Rock Slide'    },
          { level: 27, move: 'Sludge Bomb'   },
          { level: 30, move: 'Crunch'        },
          { level: 34, move: 'Shadow Claw'   },
          { level: 38, move: 'Poison Fang'   }
        ]
      },
      {
        number: 33,
        name: 'Nidorino',
        available: true,
        types: ['Poison'],
        abilities: ['Poison Point', 'Rivalry'],
        hiddenAbility: 'Hustle',
        aiAbility: '',
        gender: '100% male',
        catchRate: 120,
        stats: {
          hp: 61,
          atk: 72,
          def: 57,
          spa: 55,
          spd: 55,
          spe: 65
        },
        evolution: ['Nidoran♂', 'Nidorino', 'Nidoking'],
        learnset: [
          { level: 1,  move: 'Growl'         },
          { level: 1,  move: 'Poison Sting'  },
          { level: 1,  move: 'Scratch'       },
          { level: 9,  move: 'Sludge'        },
          { level: 13, move: 'Bite'          },
          { level: 16, move: 'Double Kick'   },
          { level: 21, move: 'Toxic'         },
          { level: 25, move: 'Rock Slide'    },
          { level: 28, move: 'Sludge Bomb'   },
          { level: 31, move: 'Crunch'        },
          { level: 36, move: 'Shadow Claw'   },
          { level: 40, move: 'Poison Fang'   }
        ]
      },
      {
        number: 34,
        name: 'Nidoking',
        available: true,
        types: ['Poison', 'Ground'],
        abilities: ['Poison Point', 'Rivalry'],
        hiddenAbility: 'Sheer Force',
        aiAbility: '',
        gender: '100% male',
        catchRate: 45,
        stats: {
          hp: 81,
          atk: 102,
          def: 77,
          spa: 85,
          spd: 75,
          spe: 85
        },
        evolution: ['Nidoran♂', 'Nidorino', 'Nidoking'],
        learnset: [
          { level: 1,  move: 'Earthquake'    },
          { level: 1,  move: 'Growl'         },
          { level: 1,  move: 'Poison Sting'  },
          { level: 1,  move: 'Scratch'       },
          { level: 9,  move: 'Sludge'        },
          { level: 13, move: 'Bite'          },
          { level: 16, move: 'Double Kick'   },
          { level: 21, move: 'Toxic'         },
          { level: 25, move: 'Rock Slide'    },
          { level: 28, move: 'Sludge Bomb'   },
          { level: 31, move: 'Crunch'        },
          { level: 36, move: 'Shadow Claw'   },
          { level: 42, move: 'Poison Fang'   },
          { level: 46, move: 'Drill Run'     },
          { level: 48, move: 'Megahorn'      },
          { level: 51, move: 'Head Smash'    }
        ]
      },      
  ];