window.pokemonData = [
    {
      number: 1,
      name: 'Bulbasaur',
      available: true,
      types: ['Grass', 'Poison'],
      ability: 'Overgrow',
      hiddenAbility: 'Chlorophyll',
      aiAbility: '',
      gender: '87.5% male, 12.5% female',
      catchRate: 45,
      stats: {
        hp: 45,
        atk: 49,
        def: 49,
        spa: 65,
        spd: 65,
        spe: 45
      },
      evolution: ['Bulbasaur', 'Ivysaur', 'Venusaur'],
      learnset: [
        { level: 1,  move: 'Tackle'      },
        { level: 1,  move: 'Growl'       },
        { level: 3,  move: 'Vine Whip'   },
        { level: 5,  move: 'Acid'        },
        { level: 8,  move: 'Headbutt'    },
        { level: 11, move: 'Growth'      },
        { level: 14, move: 'Poison Powder' },
        { level: 14, move: 'Sleep Powder'  },
        { level: 15, move: 'Razor Leaf'    },
        { level: 17, move: 'Take Down'     },
        { level: 20, move: 'Magical Leaf'  },
        { level: 22, move: 'Sludge Bomb'   },
        { level: 26, move: 'Seed Bomb'     },
        { level: 30, move: 'Toxic'         },
        { level: 30, move: 'Double-Edge'   },
        { level: 36, move: 'Leaf Blade'    },
        { level: 48, move: 'Giga Drain'    }
      ]
    },
    // more entries start here
    {
        number: 2,
        name: 'Ivysaur',
        available: true,
        types: ['Grass', 'Poison'],
        ability: 'Overgrow',
        hiddenAbility: 'Chlorophyll',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 60,
          atk: 62,
          def: 63,
          spa: 80,
          spd: 80,
          spe: 60
        },
        evolution: ['Bulbasaur', 'Ivysaur', 'Venusaur'],
        learnset: [
          { level: 1,  move: 'Tackle'      },
          { level: 1,  move: 'Growl'       },
          { level: 3,  move: 'Vine Whip'   },
          { level: 5,  move: 'Acid'        },
          { level: 8,  move: 'Headbutt'    },
          { level: 12, move: 'Poison Powder' },
          { level: 15, move: 'Sleep Powder'  },
          { level: 16, move: 'Mega Drain'    },
          { level: 19, move: 'Take Down'     },
          { level: 22, move: 'Magical Leaf'  },
          { level: 25, move: 'Sludge Bomb'   },
          { level: 28, move: 'Seed Bomb'     },
          { level: 31, move: 'Toxic'         },
          { level: 33, move: 'Double-Edge'   },
          { level: 55, move: 'Giga Drain'    }
        ]
      },
      {
        number: 3,
        name: 'Venusaur',
        available: true,
        types: ['Grass', 'Poison'],
        ability: 'Overgrow',
        hiddenAbility: 'Chlorophyll',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 80,
          atk: 82,
          def: 83,
          spa: 100,
          spd: 100,
          spe: 80
        },
        evolution: ['Bulbasaur', 'Ivysaur', 'Venusaur'],
        learnset: [
          { level: 1,  move: 'Giga Drain'     },
          { level: 1,  move: 'Ancient Power'  },
          { level: 1,  move: 'Tackle'         },
          { level: 1,  move: 'Growl'          },
          { level: 3,  move: 'Vine Whip'      },
          { level: 5,  move: 'Acid'           },
          { level: 8,  move: 'Headbutt'       },
          { level: 12, move: 'Poison Powder'  },
          { level: 15, move: 'Sleep Powder'   },
          { level: 18, move: 'Mega Drain'     },
          { level: 21, move: 'Take Down'      },
          { level: 25, move: 'Magical Leaf'   },
          { level: 28, move: 'Sludge Bomb'    },
          { level: 32, move: 'Seed Bomb'      },
          { level: 35, move: 'Toxic'          },
          { level: 36, move: 'Leaf Blade'     },
          { level: 40, move: 'Double-Edge'    },
          { level: 45, move: 'Earth Power'    }
        ]
      },
      {
        number: 3,
        name: 'Mega Venusaur',
        available: true,
        types: ['Grass', 'Poison'],
        ability: 'Thick Fat',
        hiddenAbility: '',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 80,
          atk: 100,
          def: 123,
          spa: 122,
          spd: 120,
          spe: 80
        },
        evolution: '',
        learnset: [
          { level: 1,  move: 'Giga Drain'     },
          { level: 1,  move: 'Ancient Power'  },
          { level: 1,  move: 'Tackle'         },
          { level: 1,  move: 'Growl'          },
          { level: 3,  move: 'Vine Whip'      },
          { level: 5,  move: 'Acid'           },
          { level: 8,  move: 'Headbutt'       },
          { level: 12, move: 'Poison Powder'  },
          { level: 15, move: 'Sleep Powder'   },
          { level: 18, move: 'Mega Drain'     },
          { level: 21, move: 'Take Down'      },
          { level: 25, move: 'Magical Leaf'   },
          { level: 28, move: 'Sludge Bomb'    },
          { level: 32, move: 'Seed Bomb'      },
          { level: 35, move: 'Toxic'          },
          { level: 36, move: 'Leaf Blade'     },
          { level: 40, move: 'Double-Edge'    },
          { level: 45, move: 'Earth Power'    }
        ]
      },
      {
        number: 3,
        name: 'Charmander',
        available: true,
        types: 'Fire',
        ability: 'Blaze',
        hiddenAbility: 'Solar Power',
        aiAbility: '',
        gender: '87.5% male, 12.5% female',
        catchRate: 45,
        stats: {
          hp: 39,
          atk: 52,
          def: 43,
          spa: 60,
          spd: 50,
          spe: 65
        },
        evolution: ['Charmander', 'Charmeleon', 'Charizard'],
        learnset: [
          { level: 1,  move: 'Scratch'     },
          { level: 1,  move: 'Growl'  },
          { level: 5,  move: 'Ember'         },
          { level: 8,  move: 'Smokescreen'          },
          { level: 11,  move: 'Bite'      },
          { level: 14,  move: 'Dragon Breath'           },
          { level: 16,  move: 'Fire Fang'       },
          { level: 20, move: 'Slash'  },
          { level: 25, move: 'Flame Burst'   },
          { level: 29, move: 'Dig'     },
          { level: 32, move: 'Flamethrower'      },
          { level: 36, move: 'Brick Break'   },
          { level: 40, move: 'Heat Wave'    },
          { level: 48, move: 'Flare Blitz'      }
        ]
      },
  ];