window.typeData = [
  {
    name: "Normal",
    weaknesses: ["Fighting"],
    resistances: [],
    typeImmunities: ["Ghost"],
    statusImmunities: [],
    otherImmunities: [],
  },
  {
    name: "Fire",
    weaknesses: ["Water", "Ground", "Rock"],
    resistances: ["Fire", "Grass", "Ice", "Bug", "Steel", "Fairy"],
    typeImmunities: [],
    statusImmunities: ["Burn"],
    otherImmunities: [],
  },
  {
    name: "Water",
    weaknesses: ["Electric", "Grass"],
    resistances: ["Fire", "Water", "Ice", "Steel"],
    typeImmunities: [],
    statusImmunities: [],
    otherImmunities: [],
  },
  {
    name: "Electric",
    weaknesses: ["Ground"],
    resistances: ["Electric", "Flying", "Steel"],
    typeImmunities: [],
    statusImmunities: ["Paralysis"],
    otherImmunities: [],
  },
  {
    name: "Grass",
    weaknesses: ["Fire", "Ice", "Poison", "Flying", "Bug"],
    resistances: ["Water", "Electric", "Grass", "Ground"],
    typeImmunities: [],
    statusImmunities: [],
    otherImmunities: ["Powder and spore moves (Sleep Powder, Spore, Stun Spore, etc.)", "Leech Seed"],
  },
  {
    name: "Ice",
    weaknesses: ["Fire", "Fighting", "Rock", "Steel"],
    resistances: ["Ice"],
    typeImmunities: [],
    statusImmunities: ["Freeze"],
    otherImmunities: [],
  },
  {
    name: "Fighting",
    weaknesses: ["Flying", "Psychic", "Fairy"],
    resistances: ["Bug", "Rock", "Dark"],
    typeImmunities: [],
    statusImmunities: [],
    otherImmunities: [],
  },
  {
    name: "Poison",
    weaknesses: ["Ground", "Psychic"],
    resistances: ["Grass", "Fighting", "Poison", "Bug", "Fairy"],
    typeImmunities: [],
    statusImmunities: ["Poison", "Badly Poisoned"],
    otherImmunities: [],
  },
  {
    name: "Ground",
    weaknesses: ["Water", "Grass", "Ice"],
    resistances: ["Poison", "Rock"],
    typeImmunities: ["Electric"],
    statusImmunities: [],
    otherImmunities: ["Electric-type moves (including Thunder Wave)"],
  },
  {
    name: "Flying",
    weaknesses: ["Electric", "Ice", "Rock"],
    resistances: ["Grass", "Fighting", "Bug"],
    typeImmunities: ["Ground"],
    statusImmunities: [],
    otherImmunities: [],
  },
  {
    name: "Psychic",
    weaknesses: ["Bug", "Ghost", "Dark"],
    resistances: ["Fighting", "Psychic"],
    typeImmunities: [],
    statusImmunities: [],
    otherImmunities: [],
  },
  {
    name: "Bug",
    weaknesses: ["Fire", "Flying", "Rock"],
    resistances: ["Grass", "Fighting", "Ground"],
    typeImmunities: [],
    statusImmunities: [],
    otherImmunities: [],
  },
  {
    name: "Rock",
    weaknesses: ["Water", "Grass", "Fighting", "Ground", "Steel"],
    resistances: ["Normal", "Fire", "Poison", "Flying"],
    typeImmunities: [],
    statusImmunities: [],
    otherImmunities: [],
  },
  {
    name: "Ghost",
    weaknesses: ["Ghost", "Dark"],
    resistances: ["Poison", "Bug"],
    typeImmunities: ["Normal", "Fighting"],
    statusImmunities: [],
    otherImmunities: ["Trapping moves (Mean Look, Block, Spider Web, etc.)"],
  },
  {
    name: "Dragon",
    weaknesses: ["Ice", "Dragon", "Fairy"],
    resistances: ["Fire", "Water", "Electric", "Grass"],
    typeImmunities: [],
    statusImmunities: [],
    otherImmunities: [],
  },
  {
    name: "Dark",
    weaknesses: ["Fighting", "Bug", "Fairy"],
    resistances: ["Ghost", "Dark"],
    typeImmunities: ["Psychic"],
    statusImmunities: [],
    otherImmunities: ["Moves with priority granted by Prankster"],
  },
  {
    name: "Steel",
    weaknesses: ["Fire", "Fighting", "Ground"],
    resistances: ["Normal", "Water", "Electric", "Grass", "Ice", "Flying", "Psychic", "Bug", "Rock", "Dragon", "Steel", "Fairy"],
    typeImmunities: ["Poison"],
    statusImmunities: ["Poison", "Badly Poisoned"],
    otherImmunities: [],
  },
  {
    name: "Fairy",
    weaknesses: ["Poison", "Steel"],
    resistances: ["Fighting", "Bug", "Dark"],
    typeImmunities: ["Dragon"],
    statusImmunities: [],
    otherImmunities: [],
  },
];